// Nombres y colores de drivers (código -> {nombre, color})
// Extraído de: https://docs.google.com/spreadsheets/d/10Jhp8hlHUM8EcY0zyMpAZMQxU90zslAeRWkLzHioz4c
const driverNombres = {
  // ST Series
  "ST000": { nombre: "Null", color: "Rojo" },
  "ST001": { nombre: "Attack Boost", color: "Rojo" },
  "ST002": { nombre: "Defense Boost", color: "Rojo" },
  "ST003": { nombre: "Speed Boost", color: "Rojo" },
  "ST004": { nombre: "HP Boost", color: "Rojo" },
  "ST005": { nombre: "Attack Inhibitor", color: "Rojo" },
  "ST006": { nombre: "Defense Inhibitor", color: "Rojo" },
  "ST007": { nombre: "Speed Inhibitor", color: "Rojo" },
  "ST008": { nombre: "HP Inhibitor", color: "Rojo" },
  "ST009": { nombre: "Piercing Bullet", color: "Rojo" },
  "ST010": { nombre: "Deadly Blow", color: "Rojo" },
  "ST011": { nombre: "Glass Cannon", color: "Rojo" },
  "ST012": { nombre: "Second Wind", color: "Rojo" },
  "ST013": { nombre: "Adrenaline Rush", color: "Rojo" },
  "ST014": { nombre: "Vampire", color: "Rojo" },
  "ST015": { nombre: "Eagle Eye", color: "Rojo" },
  "ST016": { nombre: "Sneaky", color: "Rojo" },
  "ST017": { nombre: "Chain", color: "Rojo" },
  "ST018": { nombre: "Opportunist", color: "Rojo" },
  "ST019": { nombre: "Tie Breaker", color: "Rojo" },
  "ST020": { nombre: "Night Owl", color: "Rojo" },
  "ST021": { nombre: "Early Bird", color: "Rojo" },
  "ST022": { nombre: "Loaded Dice", color: "Rojo" },
  "ST023": { nombre: "Critical Evasion", color: "Rojo" },
  "ST024": { nombre: "Backup", color: "Rojo" },
  "ST025": { nombre: "Child α", color: "Verde" },
  "ST026": { nombre: "Child β", color: "Verde" },
  "ST027": { nombre: "Adult α", color: "Verde" },
  "ST028": { nombre: "Adult β", color: "Verde" },
  "ST029": { nombre: "Perfect α", color: "Verde" },
  "ST030": { nombre: "Perfect β", color: "Verde" },
  "ST031": { nombre: "Heavy", color: "Verde" },
  "ST032": { nombre: "Happy Feet", color: "Verde" },
  "ST033": { nombre: "Grey Slayer", color: "Verde" },
  "ST034": { nombre: "Rule Breaker", color: "Verde" },
  "ST035": { nombre: "Title Defender", color: "Verde" },
  "ST036": { nombre: "Ace", color: "Verde" },
  "ST037": { nombre: "Mame Slayer", color: "Verde" },
  "ST038": { nombre: "EMP", color: "Azul" },
  "ST039": { nombre: "Destroy", color: "Azul" },
  "ST040": { nombre: "Cursed Chain", color: "Azul" },
  "ST041": { nombre: "Specialist", color: "Azul" },
  "ST042": { nombre: "Health Surge", color: "Azul" },
  "ST043": { nombre: "Annihilation", color: "Azul" },
  "ST044": { nombre: "Advanced Tactics", color: "Azul" },
  "ST045": { nombre: "Kaleidoscope", color: "Azul" },
  "ST046": { nombre: "Underdog", color: "Azul" },
  "ST047": { nombre: "Outsmarted", color: "Azul" },
  "ST048": { nombre: "Switcheroo", color: "Azul" },
  "ST049": { nombre: "Overdrive", color: "Azul" },
  "ST050": { nombre: "Even", color: "Amarillo" },
  "ST051": { nombre: "Odd", color: "Amarillo" },
  "ST052": { nombre: "Shuffle", color: "Amarillo" },
  "ST053": { nombre: "Right", color: "Amarillo" },
  "ST054": { nombre: "Left", color: "Amarillo" },
  "ST055": { nombre: "Optimal α", color: "Amarillo" },
  "ST056": { nombre: "Optimal β", color: "Amarillo" },
  "ST057": { nombre: "Low Profile", color: "Amarillo" },
  "ST058": { nombre: "Ground Wire", color: "Amarillo" },
  "ST059": { nombre: "Preemption", color: "Blanco" },
  "ST060": { nombre: "Searcher", color: "Blanco" },
  "ST061": { nombre: "Explorer", color: "Blanco" },
  "ST062": { nombre: "Optimizer", color: "Blanco" },
  "ST063": { nombre: "Expert Searcher", color: "Blanco" },
  "ST064": { nombre: "Unemployed", color: "Blanco" },
  "ST065": { nombre: "The Hidden", color: "Blanco" },

  // BO Series
  "BO001": { nombre: "Life Pursuit", color: "Rojo" },
  "BO002": { nombre: "Massacre", color: "Rojo" },
  "BO003": { nombre: "Afterimage", color: "Rojo" },
  "BO004": { nombre: "Optimal HI", color: "Amarillo" },
  "BO005": { nombre: "Ultimate Draw", color: "Amarillo" },
  "BO006": { nombre: "Royal Symphonia", color: "Rojo" },
  "BO007": { nombre: "Gigantic Injustice", color: "Verde" },

  // EX Series
  "EX000": { nombre: "Child EX", color: "Verde" },
  "EX001": { nombre: "Mame Gang", color: "Verde" },
  "EX003": { nombre: "Perfected Training", color: "Blanco" },
  "EX006": { nombre: "More than you see", color: "Blanco" },

  // W0 Series
  "W0000": { nombre: "Humungo Smash", color: "Rojo" },
  "W0001": { nombre: "Bad Manners", color: "Verde" },
  "W0002": { nombre: "Liquid Cooling", color: "Verde" },
  "W0003": { nombre: "4th File Pain", color: "Azul" },
  "W0004": { nombre: "Even Ground", color: "Amarillo" },
  "W0005": { nombre: "Slow Start", color: "Rojo" },
  "W0006": { nombre: "Perfect Timing", color: "Rojo" },
  "W0007": { nombre: "Last Stand", color: "Rojo" },
  "W0008": { nombre: "Counter Hit", color: "Rojo" },
  "W0009": { nombre: "Bug", color: "Azul" },
  "W0010": { nombre: "Glitch", color: "Azul" },
  "W0011": { nombre: "Street Rules", color: "Verde" },
  "W0012": { nombre: "Thornmail", color: "Rojo" },
  "W0013": { nombre: "Warning Shot", color: "Rojo" },
  "W0014": { nombre: "Blue Period", color: "Azul" },
  "W0015": { nombre: "Lucky Roll", color: "Azul" },
  "W0016": { nombre: "Coin Flip", color: "Azul" },
  "W0017": { nombre: "Lucky Leaf", color: "Azul" },
  "W0018": { nombre: "Gambling Spirit", color: "Azul" },
  "W0019": { nombre: "Quick Fingers", color: "Azul" },
  "W0020": { nombre: "Three's a Crowd", color: "Azul" },
  "W0021": { nombre: "Teamwork", color: "Azul" },
  "W0022": { nombre: "Chameleon", color: "Rainbow" },
  "W0023": { nombre: "Compressed Data", color: "Amarillo" },
  "W0024": { nombre: "Good as Gold", color: "Amarillo" },
  "W0025": { nombre: "Reverse", color: "Verde" },
  "W0026": { nombre: "Destroy R", color: "Amarillo" },
  "W0027": { nombre: "Destroy G", color: "Rojo" },
  "W0028": { nombre: "Destroy B", color: "Verde" },
  "W0029": { nombre: "Destroy Y", color: "Azul" },
  "W0030": { nombre: "Flex Style", color: "Azul" },
  "W0031": { nombre: "Void Power", color: "Amarillo" },
  "W0032": { nombre: "Best Offensive", color: "Rojo" },
  "W0033": { nombre: "Placebo", color: "Rojo" },
  "W0034": { nombre: "One of a Kind", color: "Azul" },
  "W0035": { nombre: "Fibonacci", color: "Amarillo" },
  "W0036": { nombre: "Filth", color: "Verde" },
  "W0037": { nombre: "Diavolikal", color: "Rojo" },
  "W0038": { nombre: "Decompress Data", color: "Verde" },
  "W0039": { nombre: "Forever Red", color: "Rojo" },
  "W0040": { nombre: "Pacifist", color: "Amarillo" },
  "W0041": { nombre: "Silver Bullet", color: "Rojo" },
  "W0042": { nombre: "Overdose", color: "Rojo" },
  "W0043": { nombre: "Only Words", color: "Rojo" },
  "W0044": { nombre: "Backstabbing", color: "Rojo" },
  "W0045": { nombre: "Data Leak", color: "Azul" },
  "W0046": { nombre: "Crimson Surge", color: "Rojo" },
  "W0047": { nombre: "Espionage", color: "Azul" },
  "W0048": { nombre: "Core Unbound", color: "Amarillo" },
  "W0049": { nombre: "Auto Aim Manual", color: "Rojo" },
  "W0050": { nombre: "Eden Fruit", color: "Verde" },
  "W0051": { nombre: "Serious Diet", color: "Blanco" },
  "W0052": { nombre: "Poison Touch", color: "Rojo" },
  "W0053": { nombre: "Free Turn", color: "Rojo" },
  "W0054": { nombre: "Heavy Load", color: "Amarillo" },
  "W0055": { nombre: "Regular Tactics", color: "Amarillo" },
  "W0056": { nombre: "Self-Destruct Button", color: "Azul" },
  "W0057": { nombre: "Berserk", color: "Verde" },
  "W0058": { nombre: "Sure Hit", color: "Rojo" },
  "W0059": { nombre: "United Hands", color: "Amarillo" },
  "W0060": { nombre: "Gluttony", color: "Verde" },
  "W0061": { nombre: "Interest Charge", color: "Rojo" },
  "W0062": { nombre: "Power of Friendship", color: "Verde" },
  "W0063": { nombre: "We Are So Back", color: "Verde" },
  "W0064": { nombre: "Toxic Move", color: "Rojo" },

  // V0 Series
  "V0000": { nombre: "Agumon", color: "Verde" },
  "V0001": { nombre: "Kokuwamon", color: "Verde" },
  "V0002": { nombre: "Greymon", color: "Verde" },
  "V0003": { nombre: "Tyranomon", color: "Verde" },
  "V0004": { nombre: "Dark Tyranomon", color: "Verde" },
  "V0005": { nombre: "V-Dramon", color: "Verde" },
  "V0006": { nombre: "Deltamon", color: "Verde" },
  "V0007": { nombre: "Thunderballmon", color: "Verde" },
  "V0008": { nombre: "Guardromon", color: "Verde" },
  "V0009": { nombre: "Metal Greymon (Virus)", color: "Verde" },
  "V0010": { nombre: "Andromon", color: "Verde" },
  "V0011": { nombre: "Mametyramon", color: "Verde" },
  "V0012": { nombre: "Aero V-Dramon", color: "Verde" },
  "V0013": { nombre: "Metal Tyranomon", color: "Verde" },
  "V0014": { nombre: "Psycho Blaster", color: "Verde" },
  "V0015": { nombre: "Megadramon", color: "Verde" },
  "V0016": { nombre: "Agumon (Black)", color: "Verde" },
  "V0017": { nombre: "Yuki Agumon", color: "Verde" },
  "V0018": { nombre: "Metal Greymon", color: "Verde" },
  "V0019": { nombre: "Mamemon", color: "Verde" },
  "V0020": { nombre: "Genocide Gear", color: "Verde" },
  "V0021": { nombre: "Alter Blade", color: "Verde" },
  "V0022": { nombre: "Red V-Dramon", color: "Verde" },
  "V0023": { nombre: "V-Dramon Black", color: "Verde" },
  "V0024": { nombre: "Instigator", color: "Verde" },
  "V0025": { nombre: "Triceramon", color: "Verde" },
  "V0026": { nombre: "Big Mamemon", color: "Verde" },
  "V0027": { nombre: "Guardromon (Gold)", color: "Verde" },
  "V0028": { nombre: "Baby Burner", color: "Verde" },
  "V0029": { nombre: "Horn Impulse", color: "Verde" },
  "V0030": { nombre: "Trident Revolver", color: "Verde" },
  "V0031": { nombre: "Horn Driver", color: "Verde" },
  "V0032": { nombre: "Absolute Zero", color: "Verde" },
  "V0033": { nombre: "Ice Clad", color: "Verde" },
  "V0034": { nombre: "Master Claw", color: "Verde" },
  "V0035": { nombre: "Clockmon", color: "Verde" },
  "V0036": { nombre: "Agumon Hakase", color: "Blanco" },

  // D Series
  "D000": { nombre: "Jack Raid", color: "Verde" },
  "D001": { nombre: "Death Charm", color: "Verde" },
  "D002": { nombre: "Necro Magic", color: "Verde" },
  "D003": { nombre: "Soul Chopper", color: "Verde" },
  "D004": { nombre: "Grave Scream", color: "Verde" },
  "D005": { nombre: "Oblivion Bird", color: "Verde" },

  // P Series
  "P000": { nombre: "Mushmon", color: "Blanco" },
  "P001": { nombre: "Chamblemon", color: "Blanco" },
  "P002": { nombre: "Fungi World", color: "Verde" },
  "P003": { nombre: "HIFA", color: "Azul" },

  // C Series
  "C000": { nombre: "Burning Field", color: "Rojo" },
  "C001": { nombre: "Nitro Reaction", color: "Rojo" },
  "C002": { nombre: "Tempered", color: "Azul" },
  "C003": { nombre: "Bioluminescence", color: "Amarillo" },
  "C004": { nombre: "Pre-parations", color: "Verde" },
  "C005": { nombre: "Sea Stealth Attack", color: "Azul" },
  "C006": { nombre: "Sky-2-High", color: "Rojo" },
  "C007": { nombre: "Groovy Trick", color: "Rojo" },
  "C008": { nombre: "Vertigo high", color: "Verde" },
  "C009": { nombre: "Snapped", color: "Rojo" },
  "C010": { nombre: "Sky Grinder", color: "Verde" },
  "C011": { nombre: "G0-tsu", color: "Rojo" },
  "C012": { nombre: "1ce-m0n", color: "Azul" },
  "C013": { nombre: "Ch1-b1", color: "Amarillo" },
  "C014": { nombre: "GATAI!", color: "Verde" },
  "C015": { nombre: "Black Lotus", color: "Amarillo" },
  "C016": { nombre: "Ancient Recall", color: "Rojo" },
  "C017": { nombre: "Deadman Hand", color: "Verde" },
  "C019": { nombre: "Living Fosil", color: "Verde" },
  "C020": { nombre: "Software Upgrade", color: "Verde" },
  "C021": { nombre: "Overcooled", color: "Verde" },
  "C022": { nombre: "Die, insect!", color: "Rojo" },
  "C023": { nombre: "Unity, precision, perfection", color: "Rojo" },
  "C024": { nombre: "Forced Combat", color: "Blanco" },
  "C025": { nombre: "Reboot Protocol", color: "Azul" },
  "C026": { nombre: "Driver Reborn", color: "Azul" },
  "C027": { nombre: "One Reaper", color: "Rojo" },
  "C028": { nombre: "Snake Rain", color: "Amarillo" },
  "C029": { nombre: "Joker", color: "Amarillo" },
  "C030": { nombre: "U.F.O.", color: "Azul" },
  "C032": { nombre: "Driver of Greed", color: "Amarillo" },
  "C034": { nombre: "Punishment", color: "Verde" },
  "C035": { nombre: "Evolution (Alpha)", color: "Verde" },
  "C036": { nombre: "Evolution (Alpha)", color: "Verde" },
  "C037": { nombre: "Advance Evolution", color: "Verde" },
  "C038": { nombre: "Advance Evolution", color: "Verde" },

  // VL Series
  "VL000": { nombre: "Pteromon", color: "Verde" },
  "VL001": { nombre: "Galemon", color: "Verde" },
  "VL002": { nombre: "Grand Galemon", color: "Verde" },

  // PR Series
  "PR000": { nombre: "DORUmon", color: "Verde" },

  // M Series
  "M000": { nombre: "Hyper Stink Shot", color: "Verde" },
  "M001": { nombre: "Hyper Smell", color: "Verde" },
  "M002": { nombre: "Monzaemon", color: "Verde" },
  "M003": { nombre: "Waru Monzaemon", color: "Verde" },
  "M004": { nombre: "Shell's Attack", color: "Verde" },
  "M005": { nombre: "Scumon", color: "Verde" },
  "M006": { nombre: "Gold Numemon", color: "Verde" },
  "M007": { nombre: "Metallic Guard", color: "Verde" },
  "M008": { nombre: "Love Serenade", color: "Verde" },
  "M009": { nombre: "Great King Scumon", color: "Verde" },
  "M010": { nombre: "Poison Mucus", color: "Verde" },
  "M011": { nombre: "Giga Heartbreak Attack", color: "Verde" },
  "M012": { nombre: "Burpmon", color: "Blanco" },
  "M013": { nombre: "Pillomon", color: "Blanco" },
  "M014": { nombre: "Nanimon", color: "Verde" },
  "M015": { nombre: "Countdown", color: "Verde" },
  "M016": { nombre: "Enigma", color: "Verde" },

  // VS Series
  "VS000": { nombre: "Pickmon", color: "Blanco" },
  "VS001": { nombre: "Starmons", color: "Verde" },
  "VS002": { nombre: "Dynamite Soul", color: "Verde" },
  "VS003": { nombre: "Starmon", color: "Verde" },
  "VS004": { nombre: "Halley Squall", color: "Verde" },
  "VS005": { nombre: "Schwarz Nebel", color: "Verde" },
  "VS006": { nombre: "Gottsumon", color: "Verde" },
  "VS007": { nombre: "Solid State", color: "Verde" },
  "VS008": { nombre: "Guard Rock", color: "Verde" },
  "VS009": { nombre: "Soul Crusher", color: "Verde" },
  "VS010": { nombre: "Soul Arbalest", color: "Verde" },
  "VS011": { nombre: "Full Star Blade", color: "Verde" },
  "VS012": { nombre: "Full Star Shuriken", color: "Verde" },
  "VS013": { nombre: "Rock Damashi", color: "Verde" },
  "VS014": { nombre: "Omega The Fusion", color: "Verde" },

  // U Series
  "U000": { nombre: "Optimal ∞", color: "Verde" },
  "U001": { nombre: "Full Metal Jacket", color: "Verde" },
  "U002": { nombre: "Platinum Filth", color: "Verde" },
  "U003": { nombre: "Ichigo Desu", color: "Verde" },
  "U004": { nombre: "Smiley Warhead", color: "Verde" },
  "U005": { nombre: "Black Death Cloud", color: "Verde" },
  "U006": { nombre: "Dramon Killers", color: "Verde" },
  "U007": { nombre: "War Blaster", color: "Verde" },

  // SP Series
  "SP000": { nombre: "Ice Spirit H", color: "Verde" },
  "SP001": { nombre: "Ice Spirit B", color: "Verde" },
  "SP002": { nombre: "Chackmon", color: "Verde" },
  "SP003": { nombre: "Blizzarmon", color: "Verde" },
  "SP004": { nombre: "Ice Spirit A", color: "Verde" }
};
