// itempedia.js — Datos de ítems del juego
// Campos: descripcion, efectoFueraDeCombate, efectoEntrenamiento, efectoBatalla,
//         precioVenta, precioCompra (null si no hay tienda), lugarObtencion,
//         clasificacion, hambre, peso, vinculo

const itemData = {

  // ===== COMIDA — VERDURAS =====
  "Verdura": {
    descripcion: "Le posibilita a tu Digimon realizar mejores entrenamientos.",
    descripcionEN: "Allows your Digimon to achieve better trainings.",
    nombreEN: "Vegetable",
    efectoFueraDeCombate: "Recupera hambre. Mejora el entrenamiento.",
    efectoEntrenamiento: "Ver guia de efectos variables",
    efectoBatalla: "",
    precioVenta: 75,
    precioCompra: "150 - 195",
    lugarObtencion: "Tienda / Drop de la red / Cajas",
    clasificacion: "Verdura",
    hambre: 10,
    peso: -3,
    vinculo: 0,
    plantable: true,
    resultadoPlantacion: "70% 2 Verdura / 30% 1 Mega Verdura",
    resultadoPlantacionHielo: "2 Verdura Congelada",
    tiempoPlantacion: 120,
    añejable: true,
    resultadoAñejado: "1 Verdura Fétida",
    duracionAñejado: 1440,
    costoAñejamiento: 40
  },
  "Mega Verdura": {
    descripcion: "Le posibilita a tu Digimon realizar mejores entrenamientos por más tiempo.",
    descripcionEN: "Allows your Digimon to achieve better trainings for a longer time.",
    nombreEN: "Mega Vegetable",
    efectoFueraDeCombate: "Recupera hambre. Mejora el entrenamiento.",
    efectoEntrenamiento: "Ver guia de efectos variables",
    efectoBatalla: "",
    precioVenta: 75,
    precioCompra: null,
    lugarObtencion: "Plantación / Drop de la red / Drop de enemigos",
    clasificacion: "Verdura",
    hambre: 15,
    peso: -4,
    vinculo: 0
  },
  "Verdura Congelada": {
    descripcion: "Verdura resistente al frío, supuestamente nutritiva... Pero la sensación...",
    descripcionEN: "A vegetable that is resistant to cold, said to be nutritious... but the feeling...",
    nombreEN: "Frozen Vegetable",
    efectoFueraDeCombate: "Recupera hambre. Mejora el entrenamiento. Afecta el vínculo.",
    efectoEntrenamiento: "Ver guia de efectos variables",
    efectoBatalla: "",
    precioVenta: 50,
    precioCompra: null,
    lugarObtencion: "Plantación / Drop de enemigos",
    clasificacion: "Verdura",
    hambre: 10,
    peso: -3,
    vinculo: -3,
    vinculoCondicionBase: "No Hielo",
    vinculoCondicionBaseEN: "Non-Ice",
    vinculoBonus: 3,
    vinculoCondicion: "Hielo",
    vinculoCondicionEN: "Ice",
    plantable: true,
    resultadoPlantacion: "3 Verdura Congelada",
    tiempoPlantacion: 180
  },
  "Verdura Fétida": {
    descripcion: "Verdura curada con un aroma intenso. A raíz de este, la mayoría no puede aprovechar sus propiedades y la detesta.",
    descripcionEN: "Cured vegetable with an intense aroma. Because of it, most cannot take advantage of its properties and detest it.",
    nombreEN: "Fermented Vegetable",
    efectoFueraDeCombate: "Recupera hambre. Mejora el entrenamiento. Afecta el vínculo.",
    efectoEntrenamiento: "Ver guia de efectos variables",
    efectoBatalla: "",
    precioVenta: 100,
    precioCompra: null,
    lugarObtencion: "Añejamiento",
    clasificacion: "Verdura",
    hambre: 30,
    peso: -5,
    vinculo: 0,
    vinculoCondicionBase: "Super Low Tier",
    vinculoCondicionBaseEN: "Super Low Tier",
    vinculoBonus: -10,
    vinculoCondicion: "No Low Tier / Superior",
    vinculoCondicionEN: "Non-Low Tier / Superior"
  },

  // ===== COMIDA — CARNES =====
  "Carne": {
    descripcion: "Llena un poco a tu Digimon.",
    descripcionEN: "Fills your Digimon a bit.",
    nombreEN: "Meat",
    efectoFueraDeCombate: "Recupera hambre",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 12,
    precioCompra: "25 - 33",
    lugarObtencion: "Tienda / Caja",
    clasificacion: "Carne",
    hambre: 10,
    peso: 2,
    vinculo: 0,
    plantable: true,
    resultadoPlantacion: "1 Carne Grande",
    tiempoPlantacion: 120,
    añejable: true,
    resultadoAñejado: "1 Carne Añejada",
    duracionAñejado: 1440,
    costoAñejamiento: 40
  },
  "Carne Grande": {
    descripcion: "Llena mucho a tu Digimon.",
    descripcionEN: "Fills your Digimon a lot.",
    nombreEN: "Big Meat",
    efectoFueraDeCombate: "Recupera hambre",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 50,
    precioCompra: null,
    lugarObtencion: "Plantación / Caja",
    clasificacion: "Carne",
    hambre: 25,
    peso: 4,
    vinculo: 0,
    plantable: true,
    resultadoPlantacion: "1 Solomillo",
    tiempoPlantacion: 180
  },
  "Solomillo": {
    descripcion: "Llena en exceso a tu Digimon.",
    descripcionEN: "Fills your Digimon in excess.",
    nombreEN: "Sirloin",
    efectoFueraDeCombate: "Recupera hambre. Da vínculo si llena a tu digi al 100%",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 100,
    precioCompra: null,
    lugarObtencion: "Plantación / Drops de la Red",
    clasificacion: "Carne",
    hambre: 60,
    peso: 8,
    vinculo: 0,
    vinculoBonus: 2,
    vinculoCondicion: "Si llena al 100%",
    vinculoCondicionEN: "If it fills to 100%",
    plantable: true,
    resultadoPlantacion: "1 Carne Anómala",
    tiempoPlantacion: 60
  },
  "Carne Anómala": {
    descripcion: "Esta \"carne\" desprende un olor nauseabundo, su textura y color no son para nada apetecibles y... parece estar... ¿chorreando? Dicen que es nutritiva...",
    descripcionEN: "This \"meat\" has a disgusting smell, its texture and color aren't appetizing at all and... is it dripping? They say its nutritious...",
    nombreEN: "Anomaly Meat",
    efectoFueraDeCombate: "Sube Peso. Mejora el entrenamiento y da Vínculo en digis que coman desperdicios",
    efectoEntrenamiento: "Ver guia de efectos variables",
    efectoBatalla: "",
    precioVenta: 5,
    precioCompra: "10 - 13",
    lugarObtencion: "Plantación / Caja / Tienda",
    clasificacion: "Carne",
    hambre: 0,
    peso: 5,
    vinculo: -10,
    vinculoCondicionBase: "No come caca",
    vinculoCondicionBaseEN: "Doesn't eat poop",
    vinculoBonus: 5,
    vinculoCondicion: "Come caca",
    vinculoCondicionEN: "Eats poop"
  },
  "Carne X": {
    descripcion: "Carne mortal, que engendra \"gusanos de partícula\" en su interior, capaces de eliminar al 99% de los Digimon que la consuman.",
    descripcionEN: "Deadly meat that spawns \"particle worms\" within it, capable of eliminating 99% of the Digimon that consume it.",
    nombreEN: "Meat X",
    efectoFueraDeCombate: "Mata al digi que no tenga Anticuerpo X. Intercambiable por Cepas o para misión",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 15,
    precioCompra: null,
    lugarObtencion: "Drop de la red / Drop de enemigo",
    clasificacion: "Carne",
    hambre: 0,
    peso: 0,
    vinculo: ""
  },
  "Carne Añejada": {
    descripcion: "Carne madurada durante un tiempo en la tienda del vendedor… Tiene datos concentrados que resultan beneficiosos para el Digimon.",
    descripcionEN: "Meat aged for some time inside the shopkeeper's place... A lot of data condensed on it making it a great food for Digimon.",
    nombreEN: "Aged Meat",
    efectoFueraDeCombate: "Recupera hambre. Da Entrenamiento.",
    efectoEntrenamiento: "Ver guia de efectos variables",
    efectoBatalla: "",
    precioVenta: 100,
    precioCompra: null,
    lugarObtencion: "Añejamiento",
    clasificacion: "Carne",
    hambre: 50,
    peso: 5,
    vinculo: "",
    añejable: true,
    resultadoAñejado: "1 Carne Densa",
    duracionAñejado: 1440,
    costoAñejamiento: 50
  },
  "Carne Densa": {
    descripcion: "Carne que se ha madurado durante un buen tiempo en la tienda del vendedor… Los datos, sabor y nutrientes se han condensado de forma perfecta e inaudita. Llena en extremo a tu Digimon y es muy beneficiosa.",
    descripcionEN: "Meat aged for a long time inside the shopkeeper's place... Its data, flavor and nutrients have condensed in a perfect way. Fills your Digimon a lot and has lots of benefits.",
    nombreEN: "Dense Meat",
    efectoFueraDeCombate: "Recupera hambre. Da Entrenamiento.",
    efectoEntrenamiento: "Ver guia de efectos variables",
    efectoBatalla: "",
    precioVenta: 150,
    precioCompra: null,
    lugarObtencion: "Añejamiento de Carne Añejada",
    clasificacion: "Carne",
    hambre: 75,
    peso: 10,
    vinculo: "",
    plantable: true,
    resultadoPlantacion: "1 Carne Jurásica",
    tiempoPlantacion: 720
  },
  "Carne Jurásica": {
    descripcion: "La carne de las carnes. Su data se ha condensado a niveles imposibles. Tiene una capa externa sólida y dura que hace imposible que Digimon de nivel Child o inferior puedan comerla... Sin embargo, sus beneficios son absolutos.",
    descripcionEN: "The meat of meats, its data has condensed at a never seen before level. It has an extremely hard outer layer, making it imposisible for Child or lower Digimon to eat it... however, its benefits are absolute.",
    nombreEN: "Jurassic Meat",
    efectoFueraDeCombate: "Recupera hambre. Da Entrenamiento. Añade 5 min extra de vida. Solo puede ser comida por Adultos",
    efectoEntrenamiento: "Ver guia de efectos variables",
    efectoBatalla: "",
    precioVenta: 250,
    precioCompra: null,
    lugarObtencion: "Plantación",
    clasificacion: "Carne",
    hambre: 100,
    peso: 10,
    vinculo: ""
  },
  "Ración": {
    descripcion: "Dicen que con hambre cualquier comida es un manjar...",
    descripcionEN: "When you are hungry, any food is a delicacy...",
    nombreEN: "Ration",
    efectoFueraDeCombate: "Recupera hambre.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: "",
    precioCompra: null,
    lugarObtencion: "Tienda bajo condición (quedándote sin ninguna comida y sin bits)",
    clasificacion: "Consumible",
    hambre: 10,
    peso: 2,
    vinculo: ""
  },

  // ===== COMIDA — HONGOS =====
  "Champiñón": {
    descripcion: "Llena un poco a tu Digimon.",
    descripcionEN: "Fills your Digimon a bit.",
    nombreEN: "Mushroom",
    efectoFueraDeCombate: "Recupera hambre",
    efectoEntrenamiento: "",
    efectoBatalla: "Ver guia de efectos multiples",
    precioVenta: 12,
    precioCompra: null,
    lugarObtencion: "Drops de la Red / Drops de enemigos / Caja",
    clasificacion: "Hongo",
    hambre: 10,
    peso: 1,
    vinculo: "",
    plantable: true,
    resultadoPlantacion: "70%: 2 Champiñones (no hielo) / 30%: 1 Champiñón Feliz (no hielo) | 2 Champiñones Congelados (hielo)",
    tiempoPlantacion: 180,
    resultadoPlantacionChamblemon: "1 Gigantea / 1 Hongo Azul / 1 Hongo Verde (33% c/u)"
  },
  "Champiñón Feliz": {
    descripcion: "Hongo extraño que produce placer al ser ingerido a la vez que causa una \"percepción alterada\".",
    descripcionEN: "Strange mushroom that gives pleasure when eaten, while giving an altered perception.",
    nombreEN: "Happy Mushroom",
    efectoFueraDeCombate: "Recupera hambre",
    efectoEntrenamiento: "",
    efectoBatalla: "Ver guia de efectos multiples",
    precioVenta: 100,
    precioCompra: null,
    lugarObtencion: "Drops de la Red / Plantación",
    clasificacion: "Hongo",
    hambre: 10,
    peso: 1,
    vinculo: "",
    plantable: true,
    resultadoPlantacion: "1 Seta del Caos",
    tiempoPlantacion: 240,
    resultadoPlantacionChamblemon: "1 Gigantea / 1 Hongo Azul / 1 Hongo Verde (33% c/u)"
  },
  "Champiñón Azul": {
    descripcion: "Hongo mutante; parece absorber la materia de quien lo consume... ¿Por qué?",
    descripcionEN: "Mutant mushroom; it seems to absorb the matter of whoever consumes it... Why?",
    nombreEN: "Blue Mushroom",
    efectoFueraDeCombate: "Solo puede ser usado en Mushmon/Chamblemon. Obtienes un driver de HIFA.",
    efectoEntrenamiento: "",
    efectoBatalla: "Ver guia de efectos multiples",
    precioVenta: 100,
    precioCompra: null,
    lugarObtencion: "Plantación",
    clasificacion: "Hongo",
    hambre: 0,
    peso: -5,
    vinculo: ""
  },
  "Champiñón Congelado": {
    descripcion: "Champiñón congelado, tiene un sabor que espabila a cualquiera. Es saciante, pero odiado.",
    descripcionEN: "Frozen mushroom, its flavor jolts anyone awake. It's filling, but hated.",
    nombreEN: "Frozen Mushroom",
    efectoFueraDeCombate: "Recupera Hambre. Reduce Vínculo en digis no hielo. Aumenta vínculo en digis de hielo.",
    efectoEntrenamiento: "",
    efectoBatalla: "Ver guia de efectos multiples",
    precioVenta: 12,
    precioCompra: null,
    lugarObtencion: "Plantación",
    clasificacion: "Hongo",
    hambre: 25,
    peso: -5,
    vinculo: -3,
    vinculoCondicionBase: "No Hielo",
    vinculoCondicionBaseEN: "Non-Ice",
    vinculoBonus: 3,
    vinculoCondicion: "Hielo",
    vinculoCondicionEN: "Ice",
    plantable: true,
    resultadoPlantacion: "3 Champiñones Congelados",
    tiempoPlantacion: 240,
    resultadoPlantacionChamblemon: "1 Gigantea / 1 Hongo Azul / 1 Hongo Verde (33% c/u)"
  },
  "Hongo Extraño": {
    descripcion: "Un hongo encontrado en una caja de Bacomon... Es extremadamente raro y peculiar.",
    descripcionEN: "A mushroom found on Bacomon's box... It's extremely rare and peculiar.",
    nombreEN: "Strange Mushroom",
    efectoFueraDeCombate: "Recupera Hambre. Baja Peso.",
    efectoEntrenamiento: "Ver guia de efectos variables",
    efectoBatalla: "Ver guia de efectos multiples",
    precioVenta: 200,
    precioCompra: null,
    lugarObtencion: "Cajas / Bebida Fermentada en Puppet",
    clasificacion: "Hongo",
    hambre: 15,
    peso: -5,
    vinculo: "",
    plantable: true,
    resultadoPlantacion: "1 Hongo Magnífico",
    tiempoPlantacion: 1440,
    resultadoPlantacionChamblemon: "1 Gigantea / 1 Hongo Azul / 1 Hongo Verde (33% c/u)"
  },
  "Hongo Magnífico": {
    descripcion: "Hongo que estuvo plantado durante mucho tiempo. Tiene propiedades sorprendentes.",
    descripcionEN: "A mushroom that has been planted for a long time. It has incredible properties.",
    nombreEN: "Magnificent Mushroom",
    efectoFueraDeCombate: "Recupera Hambre. Baja Peso.",
    efectoEntrenamiento: "Ver guia de efectos variables",
    efectoBatalla: "Ver guia de efectos multiples",
    precioVenta: 400,
    precioCompra: null,
    lugarObtencion: "Plantación",
    clasificacion: "Hongo",
    hambre: -10,
    peso: 30,
    vinculo: ""
  },
  "Seta del Caos": {
    descripcion: "Extraño hongo del que se percibe poder y rechazo por igual.",
    descripcionEN: "Strange mushroom from which you feel power and rejection equally.",
    nombreEN: "Chaos Mushroom",
    efectoFueraDeCombate: "Recupera Hambre. Da un Error excepto Raremon, Mushmon y Chamblemon. Disminuye Peso.",
    efectoEntrenamiento: "Ver guia de efectos variables",
    efectoBatalla: "Ver guia de efectos multiples",
    precioVenta: 100,
    precioCompra: null,
    lugarObtencion: "Plantación / Drops de la Red",
    clasificacion: "Hongo",
    hambre: 30,
    peso: -2,
    vinculo: ""
  },
  "Hongo Verde": {
    descripcion: "Hongo mutante; parece absorber la materia de quien lo consume... ¿Por qué?",
    descripcionEN: "Mutant mushroom; it seems to absorb the matter of whoever consumes it... Why?",
    nombreEN: "Green Mushroom",
    efectoFueraDeCombate: "Solo puede ser usado en Mushmon/Chamblemon. Obtienes un driver de Fungi World.",
    efectoEntrenamiento: "",
    efectoBatalla: "Ver guia de efectos multiples",
    precioVenta: 100,
    precioCompra: null,
    lugarObtencion: "Plantación",
    clasificacion: "Hongo",
    hambre: 0,
    peso: -5,
    vinculo: ""
  },
  "Hongo Lunar": {
    descripcion: "Hongo descubierto por el \"Hongomaniaco\". Se dice que aprovecha la energía nocturna...",
    descripcionEN: "Mushroom discovered by the \"Shroomaniac\", it is said to take advantage of moonlight...",
    nombreEN: "Lunar Mushroom",
    efectoFueraDeCombate: "Recupera Hambre. Aumenta Vínculo. Disminuye Peso.",
    efectoEntrenamiento: "Ver guia de efectos variables",
    horaArgentina: 0,
    efectoBatalla: "Ver guia de efectos multiples",
    precioVenta: 150,
    precioCompra: null,
    lugarObtencion: "Hongomaniaco (50% de probabilidad por 3 hongos y 100 bits)",
    clasificacion: "Hongo",
    hambre: 30,
    peso: -2,
    vinculo: 5
  },
  "Hongo Solar": {
    descripcion: "Hongo descubierto por el \"Hongomaniaco\". Se dice que aprovecha la energía diurna...",
    descripcionEN: "Mushroom discovered by the \"Shroomaniac\", it is said to take advantage of daylight...",
    nombreEN: "Solar Mushroom",
    efectoFueraDeCombate: "Recupera Hambre. Aumenta Vínculo. Disminuye Peso.",
    efectoEntrenamiento: "Ver guia de efectos variables",
    horaArgentina: 12,
    efectoBatalla: "Ver guia de efectos multiples",
    precioVenta: 150,
    precioCompra: null,
    lugarObtencion: "Hongomaniaco (50% de probabilidad por 3 hongos y 100 bits)",
    clasificacion: "Hongo",
    hambre: 30,
    peso: 2,
    vinculo: 5
  },

  // ===== COMIDA — FRUTAS =====
  "Manzana": {
    descripcion: "Una simple manzana. A veces el vendedor las trae.",
    descripcionEN: "A regular apple, sometimes the shopkeeper brings them.",
    nombreEN: "Apple",
    efectoFueraDeCombate: "Recupera Hambre.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 40,
    precioCompra: "80 - 104",
    lugarObtencion: "Tienda / Drop de la red / Cajas",
    clasificacion: "Manzana",
    hambre: 10,
    peso: 2,
    vinculo: "",
    plantable: true,
    resultadoPlantacion: "90%: 1 Manzana Azul / 10%: 1 Manzana Afortunada",
    tiempoPlantacion: 180,
    añejable: true,
    resultadoAñejado: "1 Manzana del Caos",
    duracionAñejado: 1440,
    costoAñejamiento: 40
  },
  "Manzana Azul": {
    descripcion: "Manzana muy rara obtenida mediante el cultivo. Revitaliza a tu Digimon.",
    descripcionEN: "A very rare apple obtained after harvesting, it revitalizes your Digimon.",
    nombreEN: "Blue Apple",
    efectoFueraDeCombate: "Recupera Hambre. Disminuye la fatiga utilizada en tu próxima acción a la mitad.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 80,
    precioCompra: null,
    lugarObtencion: "Plantación / Drop de enemigos / Cajas",
    clasificacion: "Manzana",
    hambre: 15,
    peso: 3,
    vinculo: "",
    plantable: true,
    resultadoPlantacion: "1 Manzana Verde",
    tiempoPlantacion: 60
  },
  "Manzana Verde": {
    descripcion: "Una manzana fétida obtenida raras veces mediante el cultivo... Se dice que los Digimon la odian en exceso...",
    descripcionEN: "A disgusting apple obtained after an unusual harvesting... It is said that Digimon hate it a lot...",
    nombreEN: "Green Apple",
    efectoFueraDeCombate: "Recupera Hambre.",
    efectoEntrenamiento: "Ver guia de efectos variables",
    efectoBatalla: "",
    precioVenta: 25,
    precioCompra: null,
    lugarObtencion: "Plantación / Cajas",
    clasificacion: "Manzana",
    hambre: 10,
    peso: -4,
    vinculo: -4,
    vinculoCondicionBase: "No Mutante",
    vinculoCondicionBaseEN: "Non-Mutant",
    vinculoBonus: 5,
    vinculoCondicion: "Mutante",
    vinculoCondicionEN: "Mutant"
  },
  "Manzana Afortunada": {
    descripcion: "Manzana peculiar. Se dice que dependiendo del momento y lugar puede causar efectos positivos o negativos.",
    descripcionEN: "Peculiar apple. It is said that depending on the time and place its effects can be positive or negative.",
    nombreEN: "Lucky Apple",
    efectoFueraDeCombate: "Recupera Hambre.",
    efectoEntrenamiento: "Ver guia de efectos variables",
    efectoBatalla: "",
    precioVenta: 150,
    precioCompra: null,
    lugarObtencion: "Plantación",
    clasificacion: "Manzana",
    hambre: 10,
    peso: 2,
    vinculo: "",
    plantable: true,
    resultadoPlantacion: "1 Manzana Verde",
    tiempoPlantacion: 180
  },
  "Manzana del Caos": {
    descripcion: "Manzana que vuelve loco a quien la consume. Da grandes beneficios en combate a costa de la integridad de su usuario.",
    descripcionEN: "Apple that drives whoever consumes it mad. It grants great combat benefits at the cost of the user's integrity.",
    nombreEN: "Chaos Apple",
    efectoFueraDeCombate: "Recupera Hambre.",
    efectoEntrenamiento: "",
    efectoBatalla: "Ver guia de efectos multiples",
    precioVenta: 100,
    precioCompra: null,
    lugarObtencion: "Añejamiento",
    clasificacion: "Manzana",
    hambre: 30,
    peso: -10,
    vinculo: ""
  },
  "Limón del Juicio": {
    descripcion: "Este limón potenció tanto su capacidad de emitir un juicio que aquellos que quieran ofrecer su fuerza vital al consumirlo son recompenzados con poder.",
    descripcionEN: "This lemon improved its judgment so much that it's capable of giving huge power to those willing to sacrifice their vital strength.",
    nombreEN: "Lemon of Judgement",
    efectoFueraDeCombate: "Recupera Hambre. Tiene un % de matarte dependiendo de la cantidad de errores que tengas ((Cantidad de Errores/6)*100) te da el %). Aumenta 1 año de vida de tu digimon.",
    efectoEntrenamiento: "Ver guia de efectos variables",
    efectoBatalla: "",
    precioVenta: 400,
    precioCompra: null,
    lugarObtencion: "Plantación",
    clasificacion: "Fruta",
    hambre: 20,
    peso: 8,
    vinculo: ""
  },
  "Limón Juzgador": {
    descripcion: "Limón vivo que al ser ingerido juzga las acciones de quien lo consume y en base a ello emite un juicio.",
    descripcionEN: "Sentient lemon that judges the action of those who eat it and emits a veredict.",
    nombreEN: "Judgemental Lemon",
    efectoFueraDeCombate: "Recupera Hambre. Solo en Baby 1 y 2 da vinculo +5.",
    efectoEntrenamiento: "Ver guia de efectos variables",
    efectoBatalla: "",
    precioVenta: 200,
    precioCompra: null,
    lugarObtencion: "Drop de la red / Bebida Fermentada en Puppet",
    clasificacion: "Fruta",
    hambre: 10,
    peso: 4,
    vinculo: "",
    vinculoBonus: 5,
    vinculoCondicion: "Baby 1 y 2",
    vinculoCondicionEN: "Baby 1 and 2",
    plantable: true,
    resultadoPlantacion: "1 Limón del Juicio",
    tiempoPlantacion: 1800
  },
  "Melón Encadenado": {
    descripcion: "Un melón extraño que rebosa de energía",
    descripcionEN: "A strange melon that overflows with energy",
    nombreEN: "Chain Melon",
    efectoFueraDeCombate: "Recupera Hambre. Aumenta 10h al timer evolutivo.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 400,
    precioCompra: null,
    lugarObtencion: "Ranking de PvP / Cajas",
    clasificacion: "Fruta",
    hambre: 20,
    peso: 2,
    vinculo: ""
  },
  "Tomate Milagroso": {
    descripcion: "Por algún motivo este tomate desprende energía… ¿sagrada?",
    descripcionEN: "Somehow this tomato emanates... Holy energy?",
    nombreEN: "Miraculous Tomato",
    efectoFueraDeCombate: "Recupera Hambre.",
    efectoEntrenamiento: "Ver guia de efectos variables",
    efectoBatalla: "",
    precioVenta: 125,
    precioCompra: null,
    lugarObtencion: "Drop de la red / Bebida Fermentada en Puppet / Cajas",
    clasificacion: "Fruta",
    hambre: 10,
    peso: -1,
    vinculo: ""
  },
  "Fruta del Diablo A": {
    descripcion: "Fruta misteriosa con propiedades desconocidas. Se dice entre Tamers que al consumirla y entrenar, ocurre algo extraño.",
    descripcionEN: "Mysterious fruit with unknown properties. It is said among tamers that if you eat it before training something strange happens...",
    nombreEN: "Devil Fruit B",
    efectoFueraDeCombate: "Recupera Hambre.",
    efectoEntrenamiento: "Ver guia de efectos variables",
    efectoBatalla: "",
    precioVenta: 150,
    precioCompra: null,
    lugarObtencion: "Cajas",
    clasificacion: "Fruta",
    hambre: 10,
    peso: 3,
    vinculo: ""
  },
  "Fruta del Diablo R": {
    descripcion: "Fruta misteriosa con propiedades desconocidas. Se dice entre Tamers que al consumirla y entrenar, ocurre algo extraño.",
    descripcionEN: "Mysterious fruit with unknown properties. It is said among tamers that if you eat it before training something strange happens...",
    nombreEN: "Devil Fruit R",
    efectoFueraDeCombate: "Recupera Hambre.",
    efectoEntrenamiento: "Ver guia de efectos variables",
    efectoBatalla: "",
    precioVenta: 150,
    precioCompra: null,
    lugarObtencion: "Cajas",
    clasificacion: "Fruta",
    hambre: 10,
    peso: 3,
    vinculo: ""
  },
  "Fruta del Diablo V": {
    descripcion: "Fruta misteriosa con propiedades desconocidas. Se dice entre Tamers que al consumirla y entrenar, ocurre algo extraño.",
    descripcionEN: "Mysterious fruit with unknown properties. It is said among tamers that if you eat it before training something strange happens...",
    nombreEN: "Devil Fruit G",
    efectoFueraDeCombate: "Recupera Hambre.",
    efectoEntrenamiento: "Ver guia de efectos variables",
    efectoBatalla: "",
    precioVenta: 150,
    precioCompra: null,
    lugarObtencion: "Cajas",
    clasificacion: "Fruta",
    hambre: 10,
    peso: 3,
    vinculo: ""
  },

  // ===== COMIDA — OTROS =====
  "Zanahoria": {
    descripcion: "Mejora la eficacia de los entrenamientos.",
    descripcionEN: "Makes training more efficient.",
    nombreEN: "Carrot",
    efectoFueraDeCombate: "Recupera hambre. Mejora el entrenamiento.",
    efectoEntrenamiento: "Ver guia de efectos variables",
    efectoBatalla: "",
    precioVenta: 75,
    precioCompra: "150 - 195",
    lugarObtencion: "Tienda / Drop de la red / Cajas",
    clasificacion: "Verdura",
    hambre: 10,
    peso: -2,
    vinculo: 0,
    plantable: true,
    resultadoPlantacion: "70% 2 Zanahoria / 30% 1 Mega Zanahoria",
    tiempoPlantacion: 120,
    añejable: true,
    resultadoAñejado: "1 Verdura Fétida",
    duracionAñejado: 1440,
    costoAñejamiento: 40
  },
  "Mega Zanahoria": {
    descripcion: "Mejora la eficacia de los entrenamientos por más tiempo.",
    descripcionEN: "Makes training more efficient for a longer time.",
    nombreEN: "Mega Carrot",
    efectoFueraDeCombate: "Recupera hambre. Mejora el entrenamiento.",
    efectoEntrenamiento: "Ver guia de efectos variables",
    efectoBatalla: "",
    precioVenta: 75,
    precioCompra: null,
    lugarObtencion: "Plantación / Drop de la red / Drop de enemigos",
    clasificacion: "Verdura",
    hambre: 15,
    peso: -3,
    vinculo: 0
  },
  "Bellota": {
    descripcion: "Alimento común pero extremadamente calórico.",
    descripcionEN: "A common yet highly caloric food.",
    nombreEN: "Acorn",
    efectoFueraDeCombate: "Recupera hambre.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 15,
    precioCompra: null,
    lugarObtencion: "Drop de la red / Cajas",
    clasificacion: "Semilla",
    hambre: 20,
    peso: 10,
    vinculo: "",
    plantable: true,
    resultadoPlantacion: "90% 3 Bellota / 10% 1 Bellota de Oro",
    tiempoPlantacion: 240,
    añejable: true,
    resultadoAñejado: "1 Bellota de Hierro",
    duracionAñejado: 1440,
    costoAñejamiento: 40
  },
  "Bellota de Oro": {
    descripcion: "Bellota extremadamente rara de encontrar. Es de un extraño pero muy resistente material. Dicen que se vende por un buen precio.",
    descripcionEN: "An extremely rare accorn, it's made of a strange yet highly durable material. They say it fetches a good price.",
    nombreEN: "Golden Acorn",
    efectoFueraDeCombate: "Recupera hambre.",
    efectoEntrenamiento: "",
    efectoBatalla: "Ver guia de efectos variables",
    precioVenta: 250,
    precioCompra: null,
    lugarObtencion: "Plantación / Drop de enemigos",
    clasificacion: "Semilla",
    hambre: 5,
    peso: 50,
    vinculo: "",
    plantable: true,
    resultadoPlantacion: "1 Bellota de Cristal",
    tiempoPlantacion: 720
  },
  "Bellota de Cristal": {
    descripcion: "Frágil alimento que alberga un poder misterioso.",
    descripcionEN: "Fragile food that holds a mysterious power.",
    nombreEN: "Crystal Acorn",
    efectoFueraDeCombate: "Recupera hambre.",
    efectoEntrenamiento: "Ver guia de efectos variables",
    efectoBatalla: "",
    precioVenta: 350,
    precioCompra: null,
    lugarObtencion: "Plantación / Drop de enemigos",
    clasificacion: "Semilla",
    hambre: 20,
    peso: 5,
    vinculo: 15
  },
  "Bellota de Hierro": {
    descripcion: "Bellota que se ha endurecido cual metal a raíz de la curación. Los Digimon máquina la adoran.",
    descripcionEN: "Acorn that has hardened like metal as a result of curing. Machine Digimon adore it.",
    nombreEN: "Iron Acorn",
    efectoFueraDeCombate: "Recupera hambre.",
    efectoEntrenamiento: "",
    efectoBatalla: "Ver guia de efectos variables",
    precioVenta: 100,
    precioCompra: null,
    lugarObtencion: "Añejamiento",
    clasificacion: "Semilla",
    hambre: 30,
    peso: 20,
    vinculo: "",
    plantable: true,
    resultadoPlantacion: "1 Bellota de Oro",
    tiempoPlantacion: 840
  },
  "Papa": {
    descripcion: "Produce una falsa sensación de saciedad. Se puede sentir el poder la tierra.",
    descripcionEN: "Produces a fake sensation of saciety. You can feel earth's power.",
    nombreEN: "Potato",
    efectoFueraDeCombate: "Recupera hambre.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 50,
    precioCompra: null,
    lugarObtencion: "Plantación / Drop de enemigos / Drop de la red",
    clasificacion: "Verdura",
    hambre: 25,
    peso: -4,
    vinculo: 0,
    plantable: true,
    resultadoPlantacion: "3 Papa",
    tiempoPlantacion: 240
  },
  "Nuez Mágica": {
    descripcion: "Nuez que parece contener diversos datos de programación... tan intrincados que parecen magia...",
    descripcionEN: "A nut that appears to contain various programming data... so intricate it seems like magic...",
    nombreEN: "Magical Nut",
    efectoFueraDeCombate: "Recupera hambre. Permite evolucionar a Bakemon.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 30,
    precioCompra: null,
    lugarObtencion: "Drop de enemigos",
    clasificacion: "Semilla",
    hambre: 40,
    peso: -20,
    vinculo: ""
  },
  "Pildora": {
    descripcion: "Acelera el metabolismo de tu digimon.",
    descripcionEN: "Speeds up your Digimon's metabolism.",
    nombreEN: "Pill",
    efectoFueraDeCombate: "Reduce el peso y aumenta el hambre.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 25,
    precioCompra: "50 - 65",
    lugarObtencion: "Tienda / Cajas",
    clasificacion: "Consumible",
    hambre: -10,
    peso: -2,
    vinculo: ""
  },
  "Medicina": {
    descripcion: "Cura las heridas y enfermedades de tu Digimon.",
    descripcionEN: "Heals your Digimon's wounds and sickness.",
    nombreEN: "Medicine",
    efectoFueraDeCombate: "Cura heridas y enfermedades.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 200,
    precioCompra: "400 - 520",
    lugarObtencion: "Tienda / Cajas",
    clasificacion: "Consumible",
    hambre: "",
    peso: "",
    vinculo: ""
  },
  "Bebida Deportiva": {
    descripcion: "Ideal para obtener resultados óptimos.",
    descripcionEN: "Ideal to achieve optimal results.",
    nombreEN: "Sports Drink",
    efectoFueraDeCombate: "Afecta el entrenamiento.",
    efectoEntrenamiento: "Ver guia de efectos variables",
    efectoBatalla: "",
    precioVenta: 10,
    precioCompra: "40 - 52",
    lugarObtencion: "Tienda / Drops de enemigos",
    clasificacion: "Consumible",
    hambre: 0,
    peso: 0,
    vinculo: "",
    añejable: true,
    resultadoAñejado: "1 Bebida Carbonatada",
    duracionAñejado: 1440,
    costoAñejamiento: 32
  },
  "Bebida Carbonatada": {
    descripcion: "Bebida deportiva que al curarse adquirió propiedades inusuales. Sus efectos varían según quien la consuma.",
    descripcionEN: "Sports drink that, after curing, acquired unusual properties. Its effects vary depending on who consumes it.",
    nombreEN: "Carbonated Drink",
    efectoFueraDeCombate: "Baja Vínculo y Peso. Efectos dependientes del tipo de Digimon.",
    efectoEntrenamiento: "",
    efectoBatalla: "Ver guia de efectos variables",
    precioVenta: 80,
    precioCompra: null,
    lugarObtencion: "Añejamiento",
    clasificacion: "Consumible",
    hambre: 0,
    peso: -3,
    vinculo: -5,
    vinculoTabla: [
      { tipo: "Dragon",      tipoEN: "Dragon",    valor: -5  },
      { tipo: "Death",       tipoEN: "Death",     valor: -10 },
      { tipo: "Compuestos",  tipoEN: "Composite", valor: -20 },
      { tipo: "Máquina",     tipoEN: "Machine",   valor: -10 },
      { tipo: "Guerrero",    tipoEN: "Warrior",   valor: -5  },
      { tipo: "Mutante",     tipoEN: "Mutant",    valor: -15 },
      { tipo: "Planta",      tipoEN: "Plant",     valor: -10 },
      { tipo: "Bestia",      tipoEN: "Beast",     valor: -5  },
      { tipo: "Viento",      tipoEN: "Wind",      valor: -5  },
      { tipo: "Hielo",       tipoEN: "Ice",       valor: -10 },
      { tipo: "Dinosaurio",  tipoEN: "Dinosaur",  valor: -5  },
      { tipo: "Tierra",      tipoEN: "Earth",     valor: -10 },
      { tipo: "Marioneta",   tipoEN: "Puppet",    valor: -10 }
    ]
  },

  // ===== RESIDUOS =====
  "Caca": {
    descripcion: "Data desechada por un Digimon. ¿Por qué alguien guardaría esto?",
    descripcionEN: "Data discarded by a Digimon. Why would anyone keep this?",
    nombreEN: "Poop",
    efectoFueraDeCombate: "Recupera el hambre. Causa enfermedad a todo Digimon que no pueda comer desechos. Fertiliza tus cosechas bajándole un 10% el tiempo de cosecha.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 1,
    precioCompra: null,
    lugarObtencion: "Recogiendo cacas de tu Digimon (excepto Platinum Numemon, Platinum Scummon, Gold Numemon y Gold Guardromon)",
    clasificacion: "Fertilizante",
    hambre: 15,
    peso: 1,
    vinculo: ""
  },
  "Caca Dorada": {
    descripcion: "Data desechada por un Digimon particular. ¿Por qué brilla? Nadie lo sabe.",
    descripcionEN: "Data discarded by a strange Digimon. Why is it bright? No one knows.",
    nombreEN: "Golden Poop",
    efectoFueraDeCombate: "Recupera el hambre. Causa enfermedad a todo Digimon que no pueda comer desechos. Fertiliza tus cosechas bajándole un % el tiempo de cosecha (por confirmar).",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 2,
    precioCompra: null,
    lugarObtencion: "Recogiendo cacas de Gold Numemon o Gold Guardromon",
    clasificacion: "Fertilizante",
    hambre: 20,
    peso: 2,
    vinculo: ""
  },
  "Caca de Platino": {
    descripcion: "Data desechada por un Digimon particular. ¿Por qué brilla? Nadie lo sabe.",
    descripcionEN: "Data discarded by a strange Digimon. Why is it bright? No one knows.",
    nombreEN: "Platinum Poop",
    efectoFueraDeCombate: "Recupera el hambre. Causa enfermedad a todo Digimon que no pueda comer desechos. Fertiliza tus cosechas bajándole un % el tiempo de cosecha (por confirmar).",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 3,
    precioCompra: null,
    lugarObtencion: "Recogiendo cacas de Platinum Numemon o Platinum Scummon",
    clasificacion: "Fertilizante",
    hambre: 15,
    peso: 2,
    vinculo: ""
  },

  // ===== PESCADO =====
  "Digitrucha": {
    descripcion: "Pescado adquirido de Digimon anfibios de la Red. Llena al Digimon. Dicen que también relaja los músculos.",
    descripcionEN: "Fish obtained from amphibious Digimon found in the net, fills the Digimon. They say it relaxes the muscles.",
    nombreEN: "Digitrout",
    efectoFueraDeCombate: "Recupera hambre. Recupera 1% de stamina.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 75,
    precioCompra: null,
    lugarObtencion: "Drop de enemigos",
    clasificacion: "Pescado",
    hambre: 25,
    peso: 4,
    vinculo: ""
  },
  "Digitrucha Negra": {
    descripcion: "Pescado extremadamente raro. Tiene propiedades que resultan muy saludables para la vida.",
    descripcionEN: "An extremely rare fish, it has properties that are very beneficial for life.",
    nombreEN: "Black Digitrout",
    efectoFueraDeCombate: "Recupera hambre. Aumenta en 1h tu timer evolutivo.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 200,
    precioCompra: null,
    lugarObtencion: "Drop de enemigos",
    clasificacion: "Pescado",
    hambre: 25,
    peso: 4,
    vinculo: ""
  },
  "Digisardina": {
    descripcion: "Pescado adquirido de Digimon anfibios de la Red... Llena un poco.",
    descripcionEN: "Fish obtained from amphibious Digimon found in the net... fills a bit.",
    nombreEN: "Digisardine",
    efectoFueraDeCombate: "Recupera hambre. Permite evolucionar a ShellNumemon desde Numemon.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 25,
    precioCompra: null,
    lugarObtencion: "Drop de enemigos",
    clasificacion: "Pescado",
    hambre: 10,
    peso: 2,
    vinculo: ""
  },
  "Restos de Metal": {
    descripcion: "Restos de metal, no hay nada que destaque en ellos.",
    descripcionEN: "Scrap metal, there is nothing remarkable about it",
    nombreEN: "Scrap Metal",
    efectoFueraDeCombate: "Enferma a tu Digimon. Aumenta Vínculo en Digimon Tipo Máquina. Enferma a todo Digimon que no sea Tipo Máquina o Platinum Scummon y sus variantes.",
    efectoEntrenamiento: "",
    efectoBatalla: "Ver guia de efectos variables",
    precioVenta: 35,
    precioCompra: null,
    lugarObtencion: "Drops de enemigos / Drops de la red",
    clasificacion: "Misceláneo",
    hambre: 10,
    peso: 10,
    vinculo: 0,
    vinculoCondicionBase: "No Tipo Máquina",
    vinculoCondicionBaseEN: "Non-Machine Type",
    vinculoBonus: 1,
    vinculoCondicion: "Tipo Máquina",
    vinculoCondicionEN: "Machine Type"
  },

  // ===== PROGRAMAS =====
  "Combat Program": {
    descripcion: "Instala \"Combat Program\" en tu Digimon.",
    descripcionEN: "Installs \"Combat Program\" to your Digimon.",
    nombreEN: "Combat Program",
    efectoFueraDeCombate: "Tu digimon obtiene data del Combat Program",
    efectoEntrenamiento: "",
    efectoBatalla: "Ver guia de efectos variables",
    precioVenta: "",
    precioCompra: null,
    lugarObtencion: "Drops",
    clasificacion: "Program",
    hambre: "",
    peso: "",
    vinculo: ""
  },
  "Death Program": {
    descripcion: "Programa capaz de forzar la muerte de casi cualquier Digimon a través de protocolos forzados en su núcleo.",
    descripcionEN: "Program capable of forcing the death of nearly any Digimon through forced protocols in its core.",
    nombreEN: "Death Program",
    efectoFueraDeCombate: "Tu digimon obtiene data del Death Program",
    efectoEntrenamiento: "",
    efectoBatalla: "Ver guia de efectos variables",
    precioVenta: "",
    precioCompra: null,
    lugarObtencion: "Drops",
    clasificacion: "Program",
    hambre: "",
    peso: "",
    vinculo: ""
  },
  "Frost Program": {
    descripcion: "Instala \"Frost Program\" en tu Digimon.",
    descripcionEN: "Installs \"Frost Program\" to your Digimon.",
    nombreEN: "Frost Program",
    efectoFueraDeCombate: "Tu digimon obtiene data del Frost Program",
    efectoEntrenamiento: "",
    efectoBatalla: "Ver guia de efectos variables",
    precioVenta: "",
    precioCompra: null,
    lugarObtencion: "Drops",
    clasificacion: "Program",
    hambre: "",
    peso: "",
    vinculo: ""
  },
  "Mecha Program": {
    descripcion: "Instala \"Mecha Program\" en tu Digimon.",
    descripcionEN: "Installs \"Mecha Program\" to your Digimon.",
    nombreEN: "Mecha Program",
    efectoFueraDeCombate: "Tu digimon obtiene data del Mecha Program",
    efectoEntrenamiento: "",
    efectoBatalla: "Ver guia de efectos variables",
    precioVenta: "",
    precioCompra: null,
    lugarObtencion: "Drops",
    clasificacion: "Program",
    hambre: "",
    peso: "",
    vinculo: ""
  },
  "Mush Program": {
    descripcion: "Program resultante de la investigación del \"Hongomaníaco\"",
    descripcionEN: "Program resulting from the research of the \"Shroomaniac\"",
    nombreEN: "Mushroom Program",
    efectoFueraDeCombate: "Tu digimon obtiene data del Mush Program",
    efectoEntrenamiento: "",
    efectoBatalla: "Ver guia de efectos variables",
    precioVenta: "",
    precioCompra: null,
    lugarObtencion: "Drops",
    clasificacion: "Program",
    hambre: "",
    peso: "",
    vinculo: ""
  },
  "Ore Program": {
    descripcion: "Contiene datos terrestres de diversos minerales, rocas, y tipos de tierra.",
    descripcionEN: "Contains data from different types of minerals, rocks and soil.",
    nombreEN: "Ore Program",
    efectoFueraDeCombate: "Tu digimon obtiene data del Ore Program",
    efectoEntrenamiento: "",
    efectoBatalla: "Ver guia de efectos variables",
    precioVenta: "",
    precioCompra: null,
    lugarObtencion: "Drops",
    clasificacion: "Program",
    hambre: "",
    peso: "",
    vinculo: ""
  },
  "Trash Program": {
    descripcion: "Instala \"Trash Program\" en tu Digimon.",
    descripcionEN: "Installs \"Trash Program\" to your Digimon.",
    nombreEN: "Trash Program",
    efectoFueraDeCombate: "Tu digimon obtiene data del Trash Program",
    efectoEntrenamiento: "",
    efectoBatalla: "Ver guia de efectos variables",
    precioVenta: 500,
    precioCompra: "1000 - 1300",
    lugarObtencion: "Tienda / Drops",
    clasificacion: "Program",
    hambre: "",
    peso: "",
    vinculo: ""
  },
  "Vaccine Program": {
    descripcion: "Instala \"Vaccine Program\" en tu Digimon.",
    descripcionEN: "Installs \"Vaccine Program\" to your Digimon.",
    nombreEN: "Vaccine Program",
    efectoFueraDeCombate: "Tu digimon obtiene data del Vaccine Program",
    efectoEntrenamiento: "",
    efectoBatalla: "Ver guia de efectos variables",
    precioVenta: "",
    precioCompra: null,
    lugarObtencion: "Drops",
    clasificacion: "Program",
    hambre: "",
    peso: "",
    vinculo: ""
  },
  "Virus Program": {
    descripcion: "Instala \"Virus Program\" en tu Digimon.",
    descripcionEN: "Installs \"Virus Program\" to your Digimon.",
    nombreEN: "Virus Program",
    efectoFueraDeCombate: "Tu digimon obtiene data del Virus Program",
    efectoEntrenamiento: "",
    efectoBatalla: "Ver guia de efectos variables",
    precioVenta: "",
    precioCompra: null,
    lugarObtencion: "Drops",
    clasificacion: "Program",
    hambre: "",
    peso: "",
    vinculo: ""
  },
  "Royal Program": {
    descripcion: "Instala \"Royalty Program\" en tu Digimon.",
    descripcionEN: "Installs \"Royalty Program\" to your Digimon.",
    nombreEN: "Royalty Program",
    efectoFueraDeCombate: "Tu digimon obtiene data del Royal Program",
    efectoEntrenamiento: "",
    efectoBatalla: "Ver guia de efectos variables",
    precioVenta: "",
    precioCompra: null,
    lugarObtencion: "Drops",
    clasificacion: "Program",
    hambre: "",
    peso: "",
    vinculo: ""
  },

  "Expansión de Drivers A": {
    descripcion: "Artículo desarrollado por el mercader misterioso, capaz de expandir nuestro almacen de drivers.",
    descripcionEN: "Item developed by the mysterious merchant, capable of expanding our driver warehouse.",
    nombreEN: "Driver Expansion A",
    efectoFueraDeCombate: "Aumenta tu espacio de drivers en el Banco de Drivers +50.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: "",
    precioCompra: null,
    lugarObtencion: "Misión del tendedero",
    clasificacion: "Misceláneo",
    hambre: "",
    peso: "",
    vinculo: ""
  },

  // ===== BOOSTERS =====
  "Booster C (A)": {
    descripcion: "Un extraño objeto obtenido de Cardmon en la red, parece tener datos de Driver en su interior.",
    descripcionEN: "A strange object obtained from Cardmon on the web, looks like it has Driver data inside",
    nombreEN: "Booster C [A]",
    efectoFueraDeCombate: "Te da 2 Drivers del set de Cardmon.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 150,
    precioCompra: null,
    lugarObtencion: "Drops de enemigos",
    clasificacion: "Caja",
    hambre: "",
    peso: "",
    vinculo: ""
  },
  "Booster C (C)": {
    descripcion: "Un extraño objeto obtenido de Cardmon en la red, parece tener datos de Driver en su interior.",
    descripcionEN: "A strange object obtained from Cardmon on the web, looks like it has Driver data inside",
    nombreEN: "Booster C [C]",
    efectoFueraDeCombate: "Te da 1 Driver del set de Cardmon.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 75,
    precioCompra: null,
    lugarObtencion: "Drops de enemigos",
    clasificacion: "Caja",
    hambre: "",
    peso: "",
    vinculo: ""
  },
  "Booster C (P)": {
    descripcion: "Un extraño objeto obtenido de Cardmon en la red, parece tener datos de Driver en su interior.",
    descripcionEN: "A strange object obtained from Cardmon on the web, looks like it has Driver data inside",
    nombreEN: "Booster C [P]",
    efectoFueraDeCombate: "Te da 3 Drivers del set de Cardmon.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 225,
    precioCompra: null,
    lugarObtencion: "Drops de enemigos",
    clasificacion: "Caja",
    hambre: "",
    peso: "",
    vinculo: ""
  },

  // ===== CAJAS =====
  "Caja Básica": {
    descripcion: "Una extraña caja obtenida de Bacomon. Me pregunto qué hay dentro...",
    descripcionEN: "A strange box obtained from Bakomon. I wonder what's inside...",
    nombreEN: "Basic Box",
    efectoFueraDeCombate: "Te da un ítem al azar de un set de pool.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 250,
    precioCompra: null,
    lugarObtencion: "Drops de enemigos",
    clasificacion: "Caja",
    hambre: "",
    peso: "",
    vinculo: ""
  },
  "Caja Lunar": {
    descripcion: "Una extraña caja con un patrón de puntos obtenida de Bacomon. Me pregunto qué hay dentro...",
    descripcionEN: "A strange box with a spotted pattern obtained from Bacomon. I wonder what's inside...",
    nombreEN: "Spotted Box",
    efectoFueraDeCombate: "Te da un ítem al azar de un set de pool.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 250,
    precioCompra: null,
    lugarObtencion: "Drops de enemigos",
    clasificacion: "Caja",
    hambre: "",
    peso: "",
    vinculo: ""
  },
  "Caja con Rayas": {
    descripcion: "Una extraña caja con un patrón a rayas obtenida de Bacomon. Me pregunto qué hay dentro...",
    descripcionEN: "A strange box with a stripped pattern obtained from Bacomon. I wonder what's inside...",
    nombreEN: "Striped Box",
    efectoFueraDeCombate: "Te da un ítem al azar de un set de pool.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 250,
    precioCompra: null,
    lugarObtencion: "Drops de enemigos",
    clasificacion: "Caja",
    hambre: "",
    peso: "",
    vinculo: ""
  },
  "Caja con Listón": {
    descripcion: "Una extraña caja con un elegante listón obtenida de Bacomon. Me pregunto qué hay dentro...",
    descripcionEN: "A strange box with an elegant ribon obtained from Bacomon. I wonder what's inside...",
    nombreEN: "Elegant Box",
    efectoFueraDeCombate: "Te da un ítem al azar de un set de pool.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 250,
    precioCompra: null,
    lugarObtencion: "Drops de enemigos",
    clasificacion: "Caja",
    hambre: "",
    peso: "",
    vinculo: ""
  },
  "Caja Navideña": {
    descripcion: "Una extraña caja obtenida de Santa. Me pregunto qué hay dentro...",
    descripcionEN: "A strange box obtained from Santa. I wonder what's inside...",
    nombreEN: "Christmas Box",
    efectoFueraDeCombate: "Te da un ítem al azar de un set de pool.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 250,
    precioCompra: null,
    lugarObtencion: "Combate Anómalo",
    clasificacion: "Caja",
    hambre: "",
    peso: "",
    vinculo: ""
  },
  "Gran Paquete": {
    descripcion: "Objeto de gran tamaño destinado a ser entregado.",
    descripcionEN: "Large-sized object meant to be delivered.",
    nombreEN: "Huge Package",
    efectoFueraDeCombate: "No se utiliza. Solo se entrega en la URL del tendedero.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: "",
    precioCompra: null,
    lugarObtencion: "Misión del tendedero",
    clasificacion: "Misceláneo",
    hambre: "",
    peso: "",
    vinculo: ""
  },

  // ===== CHIPS DE BATALLA =====
  "Chip de Análisis": {
    descripcion: "Dispositivo que nos permite ver los aumentos o disminuciones pasivos de nuestro Digimon.",
    descripcionEN: "Device that allows us to see the passive increases or decreases of our Digimon.",
    nombreEN: "Analysis chip",
    efectoFueraDeCombate: "No se utiliza directamente. Permite ver los buffos activos del Digimon.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: "",
    precioCompra: null,
    lugarObtencion: "Misión del Proxy",
    clasificacion: "Misceláneo",
    hambre: "",
    peso: "",
    vinculo: ""
  },
  "Chip de Reducción A": {
    descripcion: "Chip desarrollado por Drake, permite reducir un poco el entrenamiento del Ataque.",
    descripcionEN: "Chip developed by Drake that slightly reduces Attack training.",
    nombreEN: "Reduction chip A",
    efectoFueraDeCombate: "Reduce en 1% tu ATK (Entrenamiento).",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 125,
    precioCompra: 250,
    lugarObtencion: "Tienda de Drake",
    clasificacion: "Misceláneo",
    hambre: 0,
    peso: 0,
    vinculo: ""
  },
  "Chip de Reducción H": {
    descripcion: "Chip desarrollado por Drake, permite reducir un poco el entrenamiento del HP.",
    descripcionEN: "Chip developed by Drake that slightly reduces HP training.",
    nombreEN: "Reduction chip H",
    efectoFueraDeCombate: "Reduce en 1% tu HP (Entrenamiento).",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 125,
    precioCompra: 250,
    lugarObtencion: "Tienda de Drake",
    clasificacion: "Misceláneo",
    hambre: 0,
    peso: 0,
    vinculo: ""
  },
  "Chip de Reducción S": {
    descripcion: "Chip desarrollado por Drake, permite reducir un poco el entrenamiento de la Velocidad.",
    descripcionEN: "Chip developed by Drake that slightly reduces Speed training.",
    nombreEN: "Reduction chip S",
    efectoFueraDeCombate: "Reduce en 1% tu SPD (Entrenamiento).",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 125,
    precioCompra: 250,
    lugarObtencion: "Tienda de Drake",
    clasificacion: "Misceláneo",
    hambre: 0,
    peso: 0,
    vinculo: ""
  },
  "Chip Potenciador": {
    descripcion: "Aumenta tus entrenamientos a costa de perjudicar a tu Digimon. Se dice que reacciona con los otros Chip de Drake.",
    descripcionEN: "Increases your training at the cost of harming your Digimon. It is said to react with Drake's other Chips.",
    nombreEN: "Booster chip",
    efectoFueraDeCombate: "Da un Error.",
    efectoEntrenamiento: "Ver guia de efectos variables",
    efectoBatalla: "",
    precioVenta: 100,
    precioCompra: 200,
    lugarObtencion: "Tienda de Drake",
    clasificacion: "Consumible",
    hambre: 0,
    peso: 0,
    vinculo: ""
  },
  "Mega Chip de Reducción A": {
    descripcion: "Chip desarrollado por Drake, permite reducir mucho el entrenamiento del Ataque, pero tiene un límite.",
    descripcionEN: "Chip developed by Drake that greatly reduces Attack training, but has a limit.",
    nombreEN: "Mega reduction chip A",
    efectoFueraDeCombate: "Reduce en 10% tu ATK (Entrenamiento) SOLO si el entrenamiento del stat tiene más del 35% del 100% global de tu stage.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 750,
    precioCompra: 1500,
    lugarObtencion: "Tienda de Drake",
    clasificacion: "Misceláneo",
    hambre: 0,
    peso: 0,
    vinculo: ""
  },
  "Mega Chip de Reducción H": {
    descripcion: "Chip desarrollado por Drake, permite reducir mucho el entrenamiento del HP, pero tiene un límite.",
    descripcionEN: "Chip developed by Drake that greatly reduces HP training, but has a limit.",
    nombreEN: "Mega reduction chip H",
    efectoFueraDeCombate: "Reduce en 10% tu HP (Entrenamiento) SOLO si el entrenamiento del stat tiene más del 35% del 100% global de tu stage.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 750,
    precioCompra: 1500,
    lugarObtencion: "Tienda de Drake",
    clasificacion: "Misceláneo",
    hambre: 0,
    peso: 0,
    vinculo: ""
  },
  "Mega Chip de Reducción S": {
    descripcion: "Chip desarrollado por Drake, permite reducir mucho el entrenamiento de la Velocidad, pero tiene un límite.",
    descripcionEN: "Chip developed by Drake that greatly reduces Speed training, but has a limit.",
    nombreEN: "Mega reduction chip S",
    efectoFueraDeCombate: "Reduce en 10% tu SPD (Entrenamiento) SOLO si el entrenamiento del stat tiene más del 35% del 100% global de tu stage.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 750,
    precioCompra: 1500,
    lugarObtencion: "Tienda de Drake",
    clasificacion: "Misceláneo",
    hambre: 0,
    peso: 0,
    vinculo: ""
  },
  "Carga": {
    descripcion: "Objeto desconocido obtenido en el coliseo. Dicen que revitaliza levemente a un Digimon.",
    descripcionEN: "Unknown object earned on the colosseum. It is said to revitalize Digimon a bit...",
    nombreEN: "Charge",
    efectoFueraDeCombate: "Reduce en 10% tu stamina.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 175,
    precioCompra: null,
    lugarObtencion: "Ranking de PvP",
    clasificacion: "Misceláneo",
    hambre: "",
    peso: "",
    vinculo: ""
  },
  "Sobrecarga": {
    descripcion: "Objeto desconocido obtenido en el coliseo. Dicen que revitaliza mucho a un Digimon.",
    descripcionEN: "Unknown object earned on the colosseum. It is said to revitalize Digimon a lot...",
    nombreEN: "Overload",
    efectoFueraDeCombate: "Reduce en 50% tu stamina.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 875,
    precioCompra: null,
    lugarObtencion: "Ranking de PvP",
    clasificacion: "Misceláneo",
    hambre: "",
    peso: "",
    vinculo: ""
  },
  "Sobrecarga del Caos": {
    descripcion: "Duplicado de Drake de una \"sobrecarga\". Puede recuperar a tu Digimon de su fatiga, pero a un alto coste.",
    descripcionEN: "Drake's duplicate of an \"Overload\". Can restore your Digimon from fatigue, but at a high cost.",
    nombreEN: "Chaos overload",
    efectoFueraDeCombate: "Reduce en 100% tu stamina pero aumenta tus errores de crianza en 5.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 500,
    precioCompra: 1000,
    lugarObtencion: "Tienda de Drake",
    clasificacion: "Misceláneo",
    hambre: "",
    peso: "",
    vinculo: ""
  },
  "Inhibidor": {
    descripcion: "Objeto desconocido obtenido en el coliseo. Dicen que se usa para reducir fallos...",
    descripcionEN: "Unknown object earned on the colosseum. It is said to reduce mistakes...",
    nombreEN: "Inhibitor",
    efectoFueraDeCombate: "Reduce tus errores de crianza en 1.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 500,
    precioCompra: null,
    lugarObtencion: "Ranking de PvP",
    clasificacion: "Misceláneo",
    hambre: 0,
    peso: 0,
    vinculo: ""
  },
  "Inyector 001": {
    descripcion: "Compuesto desarrollado por Drake. Consume la masa del Digimon para fortalecerlo.",
    descripcionEN: "Compound developed by Drake; it consumes the Digimon's mass to strengthen it.",
    nombreEN: "Inyector 001",
    efectoFueraDeCombate: "Disminuye Peso.",
    efectoEntrenamiento: "",
    efectoBatalla: "Ver guia de efectos variables",
    precioVenta: 200,
    precioCompra: 400,
    lugarObtencion: "Tienda de Drake",
    clasificacion: "Consumible",
    hambre: -15,
    peso: -25,
    vinculo: ""
  },
  "Inyector 002": {
    descripcion: "Compuesto desarrollado por Drake. Altera la masa del Digimon para fortalecerlo.",
    descripcionEN: "Compound developed by Drake; it alters the Digimon's mass to strengthen it.",
    nombreEN: "Inyector 002",
    efectoFueraDeCombate: "Aumenta Peso.",
    efectoEntrenamiento: "",
    efectoBatalla: "Ver guia de efectos variables",
    precioVenta: 300,
    precioCompra: 600,
    lugarObtencion: "Tienda de Drake",
    clasificacion: "Consumible",
    hambre: 0,
    peso: 25,
    vinculo: ""
  },
  "Inyector 022": {
    descripcion: "Compuesto desarrollado por la Numegirl en base a la investigación de Drake. Fuerza al Digimon a expulsar desechos y le da tolerancia a los mismos.",
    descripcionEN: "Compound developed by Numegirl based on Drake's research. It forces a Digimon to expel waste while also granting tolerance to it.",
    nombreEN: "Inyector 022",
    efectoFueraDeCombate: "Permite a tu Digimon comer caca.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 75,
    precioCompra: 150,
    lugarObtencion: "Tienda de Drake (solo ruta Numegirl)",
    clasificacion: "Consumible",
    hambre: 0,
    peso: 0,
    vinculo: ""
  },
  "Inyector 066": {
    descripcion: "Compuesto desarrollado por el Instigador en base a la investigación de Drake. Potencia al Digimon a costa de generar estrés y malestar.",
    descripcionEN: "Compound developed by the Instigator based on Drake's research. It empowers a Digimon at the cost of generating stress and discomfort.",
    nombreEN: "Inyector 066",
    efectoFueraDeCombate: "Disminuye Vínculo y hambre.",
    efectoEntrenamiento: "",
    efectoBatalla: "Ver guia de efectos variables",
    precioVenta: 250,
    precioCompra: 500,
    lugarObtencion: "Tienda de Drake (solo ruta Reaper)",
    clasificacion: "Consumible",
    hambre: -25,
    peso: 0,
    vinculo: -12
  },
  "Titanicus": {
    descripcion: "El hongo más grande que existe, producto del cultivo modificado de un Digimon",
    descripcionEN: "The largest mushroom that exists, product of a crop modified by a Digimon",
    nombreEN: "Titanicus",
    efectoFueraDeCombate: "Recupera Hambre. Solo Chamblemon: Agrega 6hr al timer de vida.",
    efectoEntrenamiento: "Ver guia de efectos variables",
    efectoBatalla: "Ver guia de efectos multiples",
    precioVenta: 110,
    precioCompra: null,
    lugarObtencion: "Plantación",
    clasificacion: "Hongo",
    hambre: 100,
    peso: 10,
    vinculo: ""
  },
  "Cepax Alpha 10": {
    descripcion: "Síntesis del \"Virus Sitthus\" no letal. Despierta el poder latente de un Digimon mediante estrés y disminuye levemente su tiempo de vida.",
    descripcionEN: "Synthesis of the non-lethal \"Sitthus Virus.\" Awakens a Digimon's latent power through stress, slightly reducing its lifespan",
    nombreEN: "Strain X Alpha-10",
    efectoFueraDeCombate: "Disminuye Peso. Disminuye Vínculo. Disminuye en 1h tu timer evolutivo.",
    efectoEntrenamiento: "",
    efectoBatalla: "Ver guia de efectos variables",
    precioVenta: 125,
    precioCompra: null,
    lugarObtencion: "Cepas (3 Carne X x 1 Cepa al azar)",
    clasificacion: "Consumible",
    hambre: -20,
    peso: 0,
    vinculo: -5
  },
  "Cepax Beta 10": {
    descripcion: "Síntesis del \"Virus Sitthus\" no letal. Despierta el poder latente de un Digimon mediante estrés y disminuye levemente su tiempo de vida.",
    descripcionEN: "Synthesis of the non-lethal \"Sitthus Virus.\" Awakens a Digimon's latent power through stress, slightly reducing its lifespan",
    nombreEN: "Strain X Beta-10",
    efectoFueraDeCombate: "Disminuye Peso. Disminuye Vínculo. Disminuye en 1h tu timer evolutivo.",
    efectoEntrenamiento: "",
    efectoBatalla: "Ver guia de efectos variables",
    precioVenta: 125,
    precioCompra: null,
    lugarObtencion: "Cepas (3 Carne X x 1 Cepa al azar)",
    clasificacion: "Consumible",
    hambre: -20,
    peso: 0,
    vinculo: -5
  },
  "Cepax Delta 10": {
    descripcion: "Síntesis del \"Virus Sitthus\" no letal. Despierta el poder latente de un Digimon mediante estrés y disminuye levemente su tiempo de vida.",
    descripcionEN: "Synthesis of the non-lethal \"Sitthus Virus.\" Awakens a Digimon's latent power through stress, slightly reducing its lifespan",
    nombreEN: "Strain X Delta-10",
    efectoFueraDeCombate: "Disminuye Peso. Disminuye Vínculo. Disminuye en 1h tu timer evolutivo.",
    efectoEntrenamiento: "",
    efectoBatalla: "Ver guia de efectos variables",
    precioVenta: 125,
    precioCompra: null,
    lugarObtencion: "Cepas (3 Carne X x 1 Cepa al azar)",
    clasificacion: "Consumible",
    hambre: -20,
    peso: 0,
    vinculo: -5
  },
  "Cepax Omega 10": {
    descripcion: "Síntesis del \"Virus Sitthus\" no letal. Despierta el poder latente de un Digimon mediante estrés y disminuye levemente su tiempo de vida. Es la cepa definitiva.",
    descripcionEN: "Synthesis of the non-lethal \"Sitthus Virus.\" Awakens a Digimon's latent power through stress, slightly reducing its lifespan. It's the definitive strain",
    nombreEN: "Strain X Omega-10",
    efectoFueraDeCombate: "Disminuye Peso. Disminuye Vínculo. Disminuye en 1h tu timer evolutivo.",
    efectoEntrenamiento: "Ver guia de efectos variables",
    efectoBatalla: "",
    precioVenta: 225,
    precioCompra: null,
    lugarObtencion: "Cepas (3 Carne X x 1 Cepa al azar)",
    clasificacion: "Consumible",
    hambre: -50,
    peso: 0,
    vinculo: -5
  },

  // ===== ESPECIALES =====
  "Fertilizante A": {
    descripcion: "Ideal para optimizar cultivos.",
    descripcionEN: "Ideal to optimize crops.",
    nombreEN: "Fertilizer A",
    efectoFueraDeCombate: "Fertiliza tus cosechas bajándole un 60% el tiempo de cosecha.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 12,
    precioCompra: "25 - 33",
    lugarObtencion: "Tienda / Drops de enemigos",
    clasificacion: "Fertilizante",
    hambre: "",
    peso: "",
    vinculo: ""
  },
  "Fertilizante B": {
    descripcion: "Ideal para duplicar cultivos.",
    descripcionEN: "Ideal to duplicate crops.",
    nombreEN: "Fertilizer B",
    efectoFueraDeCombate: "Fertiliza tus cosechas aumentando el drop x2.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 80,
    precioCompra: "160 - 208",
    lugarObtencion: "Tienda",
    clasificacion: "Fertilizante",
    hambre: "",
    peso: "",
    vinculo: ""
  },
  "Bandita": {
    descripcion: "Cura las heridas de tu Digimon.",
    descripcionEN: "Heals your Digimon's wounds.",
    nombreEN: "Bandage",
    efectoFueraDeCombate: "Cura heridas.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 100,
    precioCompra: "200 - 260",
    lugarObtencion: "Tienda / Cajas",
    clasificacion: "Consumible",
    hambre: "",
    peso: "",
    vinculo: ""
  },
  "Clave Prototipo": {
    descripcion: "Clave privada que da acceso a la serie prototipo. Alguien la anexó a los datos del coliseo hace mucho tiempo.",
    descripcionEN: "A private key that grants access to the prototype series. Someone attached it to the coliseum's data a long time ago.",
    nombreEN: "Prototype Key",
    efectoFueraDeCombate: "Desbloquea el tama de Dorumon.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 2,
    precioCompra: null,
    lugarObtencion: "Solo top 10 de PvP",
    clasificacion: "Clave",
    hambre: "",
    peso: "",
    vinculo: ""
  },
  "Datos Gek": {
    descripcion: "Diversos y muy raros fragmentos de partículas de datos de un Digimon encontrados en una anomalía. Al usarlos pueden dar forma a un Digitama.",
    descripcionEN: "Various and very rare fragments of Digimon data particles found in an anomaly. When used, they can form a Digitama.",
    nombreEN: "Gek Data",
    efectoFueraDeCombate: "Desbloquea el tama de Gekkomon.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 2,
    precioCompra: null,
    lugarObtencion: "Combate Anómalo",
    clasificacion: "Clave",
    hambre: "",
    peso: "",
    vinculo: ""
  },
  "Cresta de la Lujuria": {
    descripcion: "Contiene información de un ser muy poderoso. Si lo usa cierto Digimon, quizás...",
    descripcionEN: "Contains information from a very powerful being. If a certain Digimon were to use it, perhaps...",
    nombreEN: "Crest of Lust",
    efectoFueraDeCombate: "Si tu Digimon es compatible, evoluciona a Lilithmon cumpliendo requisitos. Si no es compatible, te da un Driver.",
    efectoEntrenamiento: "",
    efectoBatalla: "",
    precioVenta: 500,
    precioCompra: null,
    lugarObtencion: "Anómalo de Lilithmon",
    clasificacion: "Consumible",
    hambre: "",
    peso: "",
    vinculo: "",
    driverResultado: "BO008"
  },
  "Gigantea": {
    descripcion: "Hongo inmenso producto del cultivo alterado por datos de un Digimon",
    descripcionEN: "Huge mushroom, product of a crop altered by a Digimon’s data",
    nombreEN: "Gigantea",
    efectoFueraDeCombate: "Recupera Hambre.",
    efectoEntrenamiento: "",
    efectoBatalla: "Ver guia de efectos multiples",
    precioVenta: 60,
    precioCompra: null,
    lugarObtencion: "Plantación",
    clasificacion: "Hongo",
    hambre: 80,
    peso: 8,
    vinculo: "",
    plantable: true,
    resultadoPlantacion: "1 Titanicus",
    tiempoPlantacion: 180,
    resultadoPlantacionChamblemon: "1 Gigantea / 1 Hongo Azul / 1 Hongo Verde (33% c/u)"
  },
};

// Efectos de batalla variables por tipo o Digimon
// Estructura: { "NombreItem": [ { condicion: string|null, condicionEN: string|null, efecto: string, efectoEN: string } ] }
const EfectoCombate = {
  // ── Programs (SOLO PVE) ──────────────────────────────────────────────────
  "Combat Program": [
    { condicion: "SOLO PVE", condicionEN: "PVE ONLY", efecto: "Aumenta la probabilidad de aparición de combate.", efectoEN: "Increases combat encounter probability." }
  ],
  "Death Program": [
    { condicion: "SOLO PVE", condicionEN: "PVE ONLY", efecto: "Mata a tu Digimon. O permite la Death Evolution en Digimon específicos.", efectoEN: "Kills your Digimon. Or allows Death Evolution on specific Digimon." }
  ],
  "Frost Program": [
    { condicion: "SOLO PVE | Solo Tipo Hielo", condicionEN: "PVE ONLY | Ice Type only", efecto: "+?% HP / +?% DEF (por confirmar).", efectoEN: "+?% HP / +?% DEF (TBC)." }
  ],
  "Mecha Program": [
    { condicion: "SOLO PVE | Solo Tipo Máquina", condicionEN: "PVE ONLY | Machine Type only", efecto: "+30% DEF.", efectoEN: "+30% DEF." }
  ],
  "Mush Program": [
    { condicion: "SOLO PVE", condicionEN: "PVE ONLY", efecto: "Da 1 drop garantizado de 1 hongo cada vez que encuentras un objeto en la red.", efectoEN: "Guarantees 1 mushroom drop every time you find an item in the network." }
  ],
  "Ore Program": [
    { condicion: "SOLO PVE", condicionEN: "PVE ONLY", efecto: "Por confirmar.", efectoEN: "To be confirmed." }
  ],
  "Royal Program": [
    { condicion: "SOLO PVE", condicionEN: "PVE ONLY", efecto: "Aumenta la probabilidad de obtener un item raro en la red.", efectoEN: "Increases the probability of obtaining a rare item in the network." }
  ],
  "Trash Program": [
    { condicion: "SOLO PVE", condicionEN: "PVE ONLY", efecto: "Aumenta la probabilidad de obtener un objeto en la red.", efectoEN: "Increases the probability of obtaining an item in the network." }
  ],
  "Vaccine Program": [
    { condicion: "SOLO PVE | Solo Tipo Vacuna", condicionEN: "PVE ONLY | Vaccine Type only", efecto: "+10% Omnibuffo.", efectoEN: "+10% Omnibuff." }
  ],
  "Virus Program": [
    { condicion: "SOLO PVE | Solo Tipo Virus", condicionEN: "PVE ONLY | Virus Type only", efecto: "+10% Omnibuffo.", efectoEN: "+10% Omnibuff." }
  ],
  // ── Consumibles ──────────────────────────────────────────────────────────
  "Restos de Metal": [
    { condicion: "Tipo Máquina", condicionEN: "Machine Type", efecto: "+20% DEF / -10% SPD.", efectoEN: "+20% DEF / -10% SPD." },
    { condicion: "Otros",        condicionEN: "Others",       efecto: "Sin efecto en combate.", efectoEN: "No combat effect." }
  ],
  "Bellota de Hierro": [
    { condicion: "Tipo Máquina", condicionEN: "Machine Type", efecto: "+25% DEF.", efectoEN: "+25% DEF." },
    { condicion: "Otros",        condicionEN: "Others",       efecto: "Sin efecto en combate.", efectoEN: "No combat effect." }
  ],
  "Bellota de Oro": [
    { condicion: "Tipo Máquina", condicionEN: "Machine Type", efecto: "+30% DEF / -15% SPD.", efectoEN: "+30% DEF / -15% SPD." },
    { condicion: "Otros",        condicionEN: "Others",       efecto: "Sin efecto en combate.", efectoEN: "No combat effect." }
  ],
  "Manzana del Caos": [
    { condicion: null, condicionEN: null, efecto: "+15% Omnibuffo. Si haces un combate activo te provoca una herida o enfermedad.", efectoEN: "+15% Omnibuff. Causes a wound or illness if engaging in active combat." }
  ],
  "Cepax Alpha 10": [
    { condicion: null, condicionEN: null, efecto: "+30% ATK.", efectoEN: "+30% ATK." }
  ],
  "Cepax Beta 10": [
    { condicion: null, condicionEN: null, efecto: "+15% ATK / +15% SPD.", efectoEN: "+15% ATK / +15% SPD." }
  ],
  "Cepax Delta 10": [
    { condicion: null, condicionEN: null, efecto: "+50% Daño.", efectoEN: "+50% Damage." }
  ],
  "Inyector 001": [
    { condicion: null, condicionEN: null, efecto: "+20% ATK.", efectoEN: "+20% ATK." }
  ],
  "Inyector 002": [
    { condicion: null, condicionEN: null, efecto: "+20% DEF.", efectoEN: "+20% DEF." }
  ],
  "Inyector 066": [
    { condicion: null, condicionEN: null, efecto: "+6% Omnibuffo.", efectoEN: "+6% Omnibuff." }
  ],
  // ── Hongos (Solo Mushmon / Chamblemon) ───────────────────────────────────
  "Champiñón": [
    { condicion: "Solo Mushmon / Chamblemon", condicionEN: "Mushmon / Chamblemon only", efecto: "+10% HP.", efectoEN: "+10% HP." }
  ],
  "Champiñón Congelado": [
    { condicion: "Solo Mushmon / Chamblemon", condicionEN: "Mushmon / Chamblemon only", efecto: "+5% HP.", efectoEN: "+5% HP." }
  ],
  "Champiñón Feliz": [
    { condicion: "Solo Mushmon / Chamblemon", condicionEN: "Mushmon / Chamblemon only", efecto: "+15% Probabilidad de Crítico.", efectoEN: "+15% Critical Probability." }
  ],
  "Champiñón Azul": [
    { condicion: "Solo Mushmon / Chamblemon", condicionEN: "Mushmon / Chamblemon only", efecto: "+15% SPD.", efectoEN: "+15% SPD." }
  ],
  "Seta del Caos": [
    { condicion: "Solo Mushmon / Chamblemon", condicionEN: "Mushmon / Chamblemon only", efecto: "+15% Probabilidad de Crítico.", efectoEN: "+15% Critical Probability." }
  ],
  "Hongo Solar": [
    { condicion: "Solo Mushmon / Chamblemon", condicionEN: "Mushmon / Chamblemon only", efecto: "+5% ATK.", efectoEN: "+5% ATK." }
  ],
  "Hongo Lunar": [
    { condicion: "Solo Mushmon / Chamblemon", condicionEN: "Mushmon / Chamblemon only", efecto: "+5% HP.", efectoEN: "+5% HP." }
  ],
  "Hongo Extraño": [
    { condicion: "Solo Mushmon / Chamblemon", condicionEN: "Mushmon / Chamblemon only", efecto: "+4% Omnibuffo.", efectoEN: "+4% Omnibuff." }
  ],
  "Hongo Magnífico": [
    { condicion: "Solo Mushmon / Chamblemon", condicionEN: "Mushmon / Chamblemon only", efecto: "+2.5% Omnibuffo.", efectoEN: "+2.5% Omnibuff." }
  ],
  "Hongo Verde": [
    { condicion: "Solo Mushmon / Chamblemon", condicionEN: "Mushmon / Chamblemon only", efecto: "+15% HP.", efectoEN: "+15% HP." }
  ],
  "Gigantea": [
    { condicion: "Solo Mushmon / Chamblemon | Si rival tiene más stat base", condicionEN: "Mushmon / Chamblemon only | If opponent has higher base stats", efecto: "+30% DEF.", efectoEN: "+30% DEF." },
    { condicion: "Solo Mushmon / Chamblemon | Si rival tiene menos stat base", condicionEN: "Mushmon / Chamblemon only | If opponent has lower base stats",  efecto: "+10% DEF.", efectoEN: "+10% DEF." }
  ],
  "Titanicus": [
    { condicion: "Solo Mushmon / Chamblemon", condicionEN: "Mushmon / Chamblemon only", efecto: "+20% HP / +20% DEF.", efectoEN: "+20% HP / +20% DEF." }
  ],
  // ── Bebida Carbonatada (por tipo) ─────────────────────────────────────────
  "Bebida Carbonatada": [
    { condicion: "Dragon",     condicionEN: "Dragon",    efecto: "+20% ATK.",                                     efectoEN: "+20% ATK." },
    { condicion: "Death",      condicionEN: "Death",     efecto: "+20% Daño Crítico / +20% Probabilidad de Crítico.", efectoEN: "+20% Critical Damage / +20% Critical Probability." },
    { condicion: "Compuestos", condicionEN: "Composite", efecto: "Copia el driver de tu Digimon.",                efectoEN: "Copies your Digimon's driver." },
    { condicion: "Máquina",    condicionEN: "Machine",   efecto: "+15% DEF / +15% Hit Rate.",                     efectoEN: "+15% DEF / +15% Hit Rate." },
    { condicion: "Guerrero",   condicionEN: "Warrior",   efecto: "+5% Omnibuffo.",                                efectoEN: "+5% Omnibuff." },
    { condicion: "Mutante",    condicionEN: "Mutant",    efecto: "+1% a +30% Omnibuffo (al azar).",               efectoEN: "+1% to +30% Omnibuff (random)." },
    { condicion: "Planta",     condicionEN: "Plant",     efecto: "+10% HP / +10% Hit Rate.",                      efectoEN: "+10% HP / +10% Hit Rate." },
    { condicion: "Bestia",     condicionEN: "Beast",     efecto: "+10% ATK / +10% SPD.",                          efectoEN: "+10% ATK / +10% SPD." },
    { condicion: "Viento",     condicionEN: "Wind",      efecto: "+15% SPD / +15% Probabilidad de Crítico.",      efectoEN: "+15% SPD / +15% Critical Probability." },
    { condicion: "Hielo",      condicionEN: "Ice",       efecto: "+15% DEF / +15% HP.",                           efectoEN: "+15% DEF / +15% HP." },
    { condicion: "Dinosaurio", condicionEN: "Dinosaur",  efecto: "+20% ATK.",                                     efectoEN: "+20% ATK." },
    { condicion: "Tierra",     condicionEN: "Earth",     efecto: "+30% DEF.",                                     efectoEN: "+30% DEF." },
    { condicion: "Marioneta",  condicionEN: "Puppet",    efecto: "Item al azar del pool de tu etapa.",            efectoEN: "Random item from your stage's pool." }
  ]
};

// Efectos de entrenamiento variables por tipo, etapa o condición
const EfectoEntrenamiento = {
  "Bebida Deportiva": [
    { condicion: null, condicionEN: null, efecto: "Reduce el costo de hambre a 0 en tus siguientes dos entrenamientos. Remueve una flecha roja. Si eres Nanimon da un boost de entrenamiento (por confirmar números).", efectoEN: "Reduces the hunger cost to 0 for your next two trainings. Removes one red arrow. If you are Nanimon, gives a training boost (numbers TBC)." }
  ],
  "Chip Potenciador": [
    { condicion: null, condicionEN: null, efecto: "Valor del Entrenamiento x3.", efectoEN: "Training Value x3." }
  ],
  "Cepax Omega 10": [
    { condicion: null, condicionEN: null, efecto: "Da un 2% de stats a ATK/HP/SPD entrenados (6% en total).", efectoEN: "Gives 2% stats to trained ATK/HP/SPD (6% total)." }
  ],
  "Bellota de Cristal": [
    { condicion: "Baby 1", condicionEN: "Baby 1", efecto: "+2.5 ATK / +2.5 SPD / +3.2% HP planos. (~30.00% de stat base)", efectoEN: "+2.5 ATK / +2.5 SPD / +3.2% HP flat. (~30.00% of base stat)" },
    { condicion: "Baby 2", condicionEN: "Baby 2", efecto: "+2.5 ATK / +2.5 SPD / +3.2% HP planos. (~12.10% de stat base)", efectoEN: "+2.5 ATK / +2.5 SPD / +3.2% HP flat. (~12.10% of base stat)" },
    { condicion: "Child",  condicionEN: "Child",  efecto: "+2.5 ATK / +2.5 SPD / +3.2% HP planos. (~4.30% de stat base)",  efectoEN: "+2.5 ATK / +2.5 SPD / +3.2% HP flat. (~4.30% of base stat)"  },
    { condicion: "Adult",  condicionEN: "Adult",  efecto: "+2.5 ATK / +2.5 SPD / +3.2% HP planos. (~2.30% de stat base)",  efectoEN: "+2.5 ATK / +2.5 SPD / +3.2% HP flat. (~2.30% of base stat)"  },
    { condicion: "Perfect", condicionEN: "Perfect", efecto: "+2.5 ATK / +2.5 SPD / +3.2% HP planos. (~1.10% de stat base)", efectoEN: "+2.5 ATK / +2.5 SPD / +3.2% HP flat. (~1.10% of base stat)" }
  ],
  "Verdura": [
    { condicion: null, condicionEN: null, efecto: "Agrega una flecha doble por un entrenamiento.", efectoEN: "Adds a double arrow for one training." }
  ],
  "Mega Verdura": [
    { condicion: null, condicionEN: null, efecto: "Agrega una flecha doble por 3 entrenamientos.", efectoEN: "Adds a double arrow for 3 trainings." }
  ],
  "Verdura Congelada": [
    { condicion: null, condicionEN: null, efecto: "Agrega una flecha doble por un entrenamiento.", efectoEN: "Adds a double arrow for one training." }
  ],
  "Verdura Fétida": [
    { condicion: null, condicionEN: null, efecto: "Por confirmar números exactos.", efectoEN: "To be confirmed." }
  ],
  "Zanahoria": [
    { condicion: null, condicionEN: null, efecto: "Multiplica el resultado del entrenamiento x1.5 por un entrenamiento.", efectoEN: "Multiplies the training result x1.5 for one training." }
  ],
  "Mega Zanahoria": [
    { condicion: null, condicionEN: null, efecto: "Multiplica el resultado del entrenamiento x1.5 por 3 entrenamientos.", efectoEN: "Multiplies the training result x1.5 for 3 trainings." }
  ],
  "Carne Anómala": [
    { condicion: null, condicionEN: null, efecto: "Valor del Entrenamiento x 2 (Solo mutantes que coman caca)", efectoEN: "Training Value x 2 (Only for mutants that eat waste)" }
  ],
  "Carne Añejada": [
    { condicion: null, condicionEN: null, efecto: "+2 ATK Plano", efectoEN: "+2 flat ATK" }
  ],
  "Carne Densa": [
    { condicion: null, condicionEN: null, efecto: "+2.5 ATK Plano", efectoEN: "+2.5 flat ATK" }
  ],
  "Carne Jurásica": [
    { condicion: null, condicionEN: null, efecto: "+2.5 ATK Plano & +2.6% HP", efectoEN: "+2.5 flat ATK & +2.6% HP" }
  ],
  "Hongo Extraño": [
    { condicion: null, condicionEN: null, efecto: "Da un 3.33% de stats a ATK/HP/SPD entrenados (10% en total).", efectoEN: "Gives 3.33% of stats to trained ATK/HP/SPD (10% total)." }
  ],
  "Hongo Magnífico": [
    { condicion: null, condicionEN: null, efecto: "Da un 10% de stats a ATK/HP/SPD entrenados (30% en total). Si usas una Fruta del diablo previamente, aumenta el stat de la fruta en un 30% de stat entrenado.", efectoEN: "Gives 10% stats to trained ATK/HP/SPD (30% total). If you use a Devil Fruit before, increases the fruit's stat by 30% of the trained stat." }
  ],
  "Seta del Caos": [
    { condicion: null, condicionEN: null, efecto: "Valor del Entrenamiento x 3.", efectoEN: "Training Value x 3." }
  ],
  "Hongo Lunar": [
    { condicion: "12AM hora Argentina", condicionEN: "12AM Argentina time", argentinaHour: 0,  efecto: "Valor del Entrenamiento x2.6. Agrega Doble Flecha Blanca.", efectoEN: "Training Value x2.6. Adds Double White Arrow." },
    { condicion: "Resto del día",       condicionEN: "Rest of the day",                        efecto: "Sin efecto extra de entrenamiento.",                        efectoEN: "No extra training effect." }
  ],
  "Hongo Solar": [
    { condicion: "12PM hora Argentina", condicionEN: "12PM Argentina time", argentinaHour: 12, efecto: "Valor del Entrenamiento x2.6. Agrega Doble Flecha Blanca.", efectoEN: "Training Value x2.6. Adds Double White Arrow." },
    { condicion: "Resto del día",       condicionEN: "Rest of the day",                        efecto: "Sin efecto extra de entrenamiento.",                        efectoEN: "No extra training effect." }
  ],
  "Limón del Juicio": [
    { condicion: null, condicionEN: null, efecto: "Da un 2% de stats a ATK/HP/SPD entrenados (6% en total).", efectoEN: "Gives 2% stats to trained ATK/HP/SPD (6% total)." }
  ],
  "Limón Juzgador": [
    { condicion: "Child",   condicionEN: "Child",   efecto: "Multiplica x2",    efectoEN: "Multiplies x2" },
    { condicion: "Adult",   condicionEN: "Adult",   efecto: "Multiplica x2.25", efectoEN: "Multiplies x2.25" },
    { condicion: "Perfect", condicionEN: "Perfect", efecto: "Multiplica x2.5",  efectoEN: "Multiplies x2.5" }
  ],
  "Tomate Milagroso": [
    { condicion: null, condicionEN: null, efecto: "Multiplica tu entrenamiento x2. Agrega una doble flecha.", efectoEN: "Multiplies your training x2. Adds a double arrow." }
  ],
  "Fruta del Diablo A": [
    { condicion: "Velocidad",   condicionEN: "Speed",      efecto: "Multiplica entrenamiento x3. Asegura Doble Flecha, pero agrega 5 flechas rojas.", efectoEN: "Multiplies training x3. Ensures Double Arrow, but adds 5 red arrows." },
    { condicion: "ATK / HP",    condicionEN: "ATK / HP",   efecto: "Sin efecto de entrenamiento.",                                                     efectoEN: "No training effect." }
  ],
  "Fruta del Diablo R": [
    { condicion: "Ataque",      condicionEN: "Attack",     efecto: "Multiplica entrenamiento x3. Asegura Doble Flecha, pero agrega 5 flechas rojas.", efectoEN: "Multiplies training x3. Ensures Double Arrow, but adds 5 red arrows." },
    { condicion: "SPD / HP",    condicionEN: "SPD / HP",   efecto: "Sin efecto de entrenamiento.",                                                     efectoEN: "No training effect." }
  ],
  "Fruta del Diablo V": [
    { condicion: "HP",          condicionEN: "HP",         efecto: "Multiplica entrenamiento x3. Asegura Doble Flecha, pero agrega 5 flechas rojas.", efectoEN: "Multiplies training x3. Ensures Double Arrow, but adds 5 red arrows." },
    { condicion: "ATK / SPD",   condicionEN: "ATK / SPD",  efecto: "Sin efecto de entrenamiento.",                                                     efectoEN: "No training effect." }
  ],
  "Manzana Verde": [
    { condicion: "Mutante",    condicionEN: "Mutant",     efecto: "Da al azar +1.5 ATK, +1.5 SPD o +1.9% HP plano al stat entrenado", efectoEN: "Randomly gives +1.5 ATK, +1.5 SPD or +1.9% flat HP to the trained stat" },
    { condicion: "No Mutante", condicionEN: "Non-Mutant", efecto: "Sin efecto de entrenamiento",                                       efectoEN: "No training effect" }
  ],
  "Manzana Afortunada": [
    { condicion: "Días 7 y 28 del mes",   condicionEN: "Days 7 and 28 of the month", efecto: "Multiplica entrenamiento entre x1 y x3", efectoEN: "Multiplies training between x1 and x3" },
    { condicion: "Día 13 del mes",         condicionEN: "Day 13 of the month",        efecto: "Multiplica entrenamiento entre x0 y x1", efectoEN: "Multiplies training between x0 and x1" },
    { condicion: "Todos los demás días",   condicionEN: "All other days",             efecto: "Multiplica entrenamiento entre x0 y x3", efectoEN: "Multiplies training between x0 and x3" }
  ],
  "Titanicus": [
    { condicion: "Mushmon / Chamblemon", condicionEN: "Mushmon / Chamblemon", efecto: "Da un 3.33% de stats a ATK/HP/SPD entrenados (10% en total).", efectoEN: "Gives 3.33% stats to trained ATK/HP/SPD (10% total)." },
    { condicion: "Otros",                condicionEN: "Others",               efecto: "Sin efecto de entrenamiento.",                                    efectoEN: "No training effect." }
  ]
};

// Clasificaciones disponibles (para filtros)
const itemClasificaciones = [
  "Carne",
  "Hongo",
  "Fruta",
  "Manzana",
  "Verdura",
  "Semilla",
  "Pescado",
  "Consumible",
  "Fertilizante",
  "Caja",
  "Misceláneo",
  "Clave",
  "Program"
];



